source(testthat::test_path("common-functions.R"), local = environment())

bayestools_registry_flag_columns <- function() {
  c(
    "simple_priors",
    "vector_priors",
    "factor_priors",
    "pub_bias_priors",
    "weightfunction_priors",
    "spike_and_slab_priors",
    "mixture_priors",
    "formulas",
    "random_effects",
    "interactions",
    "expression_priors",
    "multi_formula",
    "autofit",
    "parallel",
    "thinning",
    "add_parameters"
  )
}

bayestools_registry_schema_columns <- function() {
  c("model_name", "has_marglik", bayestools_registry_flag_columns(), "note")
}

bayestools_model_fit_source_file <- function() {
  testthat::test_path("test-00-model-fits.R")
}

bayestools_optional_fit_requirements <- function() {
  data.frame(
    model_name = c(
      "fit_complex_mixed",
      "fit_simple_formula_mixed",
      "fit_complex_bias"
    ),
    requires_package = "RoBMA",
    stringsAsFactors = FALSE
  )
}

.bayestools_random_z_monitors <- function(stem, n_groups, n_columns) {
  as.vector(outer(
    seq_len(n_groups),
    seq_len(n_columns),
    function(group, column) paste0(stem, "[", group, ",", column, "]")
  ))
}

.bayestools_find_calls <- function(expr, fun) {
  matches <- list()

  walk <- function(x) {
    if (is.expression(x)) {
      for (item in as.list(x)) {
        walk(item)
      }
    } else if (is.call(x)) {
      head <- x[[1L]]
      if (is.symbol(head) && identical(as.character(head), fun)) {
        matches[[length(matches) + 1L]] <<- x
      }
      for (item in as.list(x)[-1L]) {
        walk(item)
      }
    }
  }

  walk(expr)
  matches
}

.bayestools_static_string <- function(expr, default = NA_character_) {
  if (is.character(expr) && length(expr) == 1L) {
    return(expr)
  }
  default
}

.bayestools_static_logical <- function(expr, default = FALSE) {
  if (is.logical(expr) && length(expr) == 1L && !is.na(expr)) {
    return(expr)
  }
  default
}

.bayestools_save_fit_catalog_rows <- function(source_file = bayestools_model_fit_source_file()) {
  if (!file.exists(source_file)) {
    stop("Model fit source file not found: ", source_file, call. = FALSE)
  }

  flag_cols <- bayestools_registry_flag_columns()
  calls <- .bayestools_find_calls(parse(source_file), "save_fit")

  rows <- lapply(calls, function(call) {
    args <- as.list(call)[-1L]
    arg_names <- names(args)
    if (is.null(arg_names)) {
      arg_names <- rep("", length(args))
    }

    get_arg <- function(name, position = NULL, default = NULL) {
      named_index <- match(name, arg_names)
      if (!is.na(named_index)) {
        return(args[[named_index]])
      }
      if (!is.null(position) && length(args) >= position && !nzchar(arg_names[[position]])) {
        return(args[[position]])
      }
      default
    }

    model_name <- .bayestools_static_string(get_arg("name", position = 2L))
    note <- .bayestools_static_string(get_arg("note"), default = "")

    flags <- vapply(flag_cols, function(flag) {
      .bayestools_static_logical(get_arg(flag), default = FALSE)
    }, logical(1))

    has_marglik <- !is.null(get_arg("marglik"))
    prior_features <- names(flags)[flags]
    if (length(prior_features) == 0L) {
      prior_features <- "none"
    }

    data.frame(
      model_name = model_name,
      profile = "fixture",
      fit_file = paste0(model_name, ".RDS"),
      marglik_file = if (has_marglik) paste0(model_name, ".RDS") else NA_character_,
      has_marglik = has_marglik,
      as.data.frame(as.list(flags), check.names = FALSE),
      model_family = "generated-fixture",
      formula = NA_character_,
      scale_policy = if (flags[["formulas"]]) "catalog-unverified" else "none",
      prior_features = paste(prior_features, collapse = ","),
      requires_package = NA_character_,
      oracle_type = "registry-metadata",
      expected_chains = NA_integer_,
      expected_iterations = NA_integer_,
      expected_parameter_count = NA_integer_,
      tolerance = NA_real_,
      note = note,
      stringsAsFactors = FALSE,
      check.names = FALSE
    )
  })

  catalog <- do.call(rbind, rows)
  optional <- bayestools_optional_fit_requirements()
  optional_index <- match(optional$model_name, catalog$model_name)
  if (anyNA(optional_index)) {
    stop(
      "Optional fit catalog entries are not generated by test-00-model-fits.R: ",
      paste(optional$model_name[is.na(optional_index)], collapse = ", "),
      call. = FALSE
    )
  }
  catalog$requires_package[optional_index] <- optional$requires_package

  catalog$expected_monitor <- I(rep(list(character()), nrow(catalog)))
  catalog$expected_formula_parameters <- I(rep(list(character()), nrow(catalog)))
  catalog$expected_formula_scale <- I(rep(list(character()), nrow(catalog)))
  rownames(catalog) <- NULL
  catalog
}

bayestools_semantic_fit_catalog_overrides <- function() {
  flag_cols <- bayestools_registry_flag_columns()

  catalog_row <- function(model_name, has_marglik, model_family,
                          formula = NA_character_, scale_policy = "none",
                          prior_features, expected_monitor,
                          expected_formula_parameters = character(),
                          expected_formula_scale = character(),
                          oracle_type = "fixture-metadata",
                          expected_chains, expected_iterations,
                          tolerance = NA_real_, flags = list(), note) {
    list(
      model_name = model_name,
      profile = "fixture",
      has_marglik = has_marglik,
      model_family = model_family,
      formula = formula,
      scale_policy = scale_policy,
      prior_features = prior_features,
      expected_monitor = expected_monitor,
      expected_formula_parameters = expected_formula_parameters,
      expected_formula_scale = expected_formula_scale,
      oracle_type = oracle_type,
      expected_chains = expected_chains,
      expected_iterations = expected_iterations,
      tolerance = tolerance,
      flags = flags,
      note = note
    )
  }

  catalog_rows <- list(
    list(
      model_name = "fit_simple_normal",
      profile = "fixture",
      has_marglik = TRUE,
      model_family = "normal-location-scale",
      formula = NA_character_,
      scale_policy = "none",
      prior_features = "simple",
      expected_monitor = c("m", "s"),
      expected_formula_parameters = character(),
      expected_formula_scale = character(),
      oracle_type = "fixture-metadata",
      expected_chains = 2L,
      expected_iterations = 500L,
      tolerance = NA_real_,
      flags = list(simple_priors = TRUE),
      note = "Normal mean and positive scale fixture with bridge marginal likelihood."
    ),
    list(
      model_name = "fit_simple_spike",
      profile = "fixture",
      has_marglik = TRUE,
      model_family = "normal-location-scale",
      formula = NA_character_,
      scale_policy = "point-prior-fixed",
      prior_features = "simple,point",
      expected_monitor = "s",
      expected_formula_parameters = character(),
      expected_formula_scale = character(),
      oracle_type = "fixture-metadata",
      expected_chains = 2L,
      expected_iterations = 500L,
      tolerance = NA_real_,
      flags = list(simple_priors = TRUE),
      note = "Spike mean fixture; deterministic point prior must not be monitored."
    ),
    list(
      model_name = "fit_simple_various",
      profile = "fixture",
      has_marglik = FALSE,
      model_family = "prior-only-scalar",
      formula = NA_character_,
      scale_policy = "point-prior-fixed",
      prior_features = "simple,point",
      expected_monitor = c("p1", "p2", "p3", "p4", "p5", "p6", "inv_p6", "p7", "p8", "p9"),
      expected_formula_parameters = character(),
      expected_formula_scale = character(),
      oracle_type = "fixture-metadata",
      expected_chains = 2L,
      expected_iterations = 500L,
      tolerance = NA_real_,
      flags = list(simple_priors = TRUE),
      note = "Prior-only scalar fixture; point prior component is deterministic and inverse-gamma exposes its inverse monitor."
    ),
    list(
      model_name = "fit_simple_pub_bias",
      profile = "fixture",
      has_marglik = FALSE,
      model_family = "prior-only-publication-bias",
      formula = NA_character_,
      scale_policy = "none",
      prior_features = "publication-bias",
      expected_monitor = c("PET", "PEESE"),
      expected_formula_parameters = character(),
      expected_formula_scale = character(),
      oracle_type = "fixture-metadata",
      expected_chains = 2L,
      expected_iterations = 500L,
      tolerance = NA_real_,
      flags = list(pub_bias_priors = TRUE),
      note = "PET and PEESE publication-bias prior fixture."
    ),
    list(
      model_name = "fit_simple_thin",
      profile = "fixture",
      has_marglik = FALSE,
      model_family = "prior-only-scalar",
      formula = NA_character_,
      scale_policy = "none",
      prior_features = "simple,thinning",
      expected_monitor = "mu",
      expected_formula_parameters = character(),
      expected_formula_scale = character(),
      oracle_type = "fixture-metadata",
      expected_chains = 2L,
      expected_iterations = 300L,
      tolerance = NA_real_,
      flags = list(simple_priors = TRUE, thinning = TRUE),
      note = "Simple normal prior fixture with thinning."
    ),
    list(
      model_name = "fit_summary0",
      profile = "fixture",
      has_marglik = TRUE,
      model_family = "normal-location-summary",
      formula = NA_character_,
      scale_policy = "none",
      prior_features = "simple,weightfunction-none",
      expected_monitor = "m",
      expected_formula_parameters = character(),
      expected_formula_scale = character(),
      oracle_type = "fixture-metadata",
      expected_chains = 1L,
      expected_iterations = 500L,
      tolerance = NA_real_,
      flags = list(simple_priors = TRUE, weightfunction_priors = TRUE),
      note = "Summary-table null weightfunction fixture with bridge marginal likelihood."
    ),
    list(
      model_name = "fit_summary1",
      profile = "fixture",
      has_marglik = TRUE,
      model_family = "normal-location-summary",
      formula = NA_character_,
      scale_policy = "none",
      prior_features = "simple,weightfunction",
      expected_monitor = c("m", "omega[1]", "omega[2]", "eta[1]", "eta[2]"),
      expected_formula_parameters = character(),
      expected_formula_scale = character(),
      oracle_type = "fixture-metadata",
      expected_chains = 1L,
      expected_iterations = 500L,
      tolerance = NA_real_,
      flags = list(simple_priors = TRUE, weightfunction_priors = TRUE),
      note = "Summary-table one-sided two-interval weightfunction fixture."
    ),
    list(
      model_name = "fit_summary2",
      profile = "fixture",
      has_marglik = TRUE,
      model_family = "normal-location-summary",
      formula = NA_character_,
      scale_policy = "none",
      prior_features = "simple,weightfunction",
      expected_monitor = c("m", "omega[1]", "omega[2]", "omega[3]", "eta[1]", "eta[2]", "eta[3]"),
      expected_formula_parameters = character(),
      expected_formula_scale = character(),
      oracle_type = "fixture-metadata",
      expected_chains = 1L,
      expected_iterations = 500L,
      tolerance = NA_real_,
      flags = list(simple_priors = TRUE, weightfunction_priors = TRUE),
      note = "Summary-table one-sided three-interval weightfunction fixture."
    ),
    list(
      model_name = "fit_summary3",
      profile = "fixture",
      has_marglik = TRUE,
      model_family = "normal-location-summary",
      formula = NA_character_,
      scale_policy = "fixed-selection",
      prior_features = "simple,weightfunction,fixed",
      expected_monitor = c("m", "omega[1]", "omega[2]", "omega[3]"),
      expected_formula_parameters = character(),
      expected_formula_scale = character(),
      oracle_type = "fixture-metadata",
      expected_chains = 1L,
      expected_iterations = 500L,
      tolerance = NA_real_,
      flags = list(simple_priors = TRUE, weightfunction_priors = TRUE),
      note = "Summary-table fixed two-sided weightfunction fixture."
    ),
    list(
      model_name = "fit_vector_mnormal",
      profile = "fixture",
      has_marglik = FALSE,
      model_family = "prior-only-vector",
      formula = NA_character_,
      scale_policy = "none",
      prior_features = "vector",
      expected_monitor = paste0("p1[", 1:3, "]"),
      expected_formula_parameters = character(),
      expected_formula_scale = character(),
      oracle_type = "fixture-metadata",
      expected_chains = 2L,
      expected_iterations = 500L,
      tolerance = NA_real_,
      flags = list(vector_priors = TRUE),
      note = "Multivariate normal prior fixture with three monitored coordinates."
    ),
    list(
      model_name = "fit_vector_mcauchy",
      profile = "fixture",
      has_marglik = FALSE,
      model_family = "prior-only-vector",
      formula = NA_character_,
      scale_policy = "none",
      prior_features = "vector",
      expected_monitor = paste0("p1[", 1:2, "]"),
      expected_formula_parameters = character(),
      expected_formula_scale = character(),
      oracle_type = "fixture-metadata",
      expected_chains = 2L,
      expected_iterations = 500L,
      tolerance = NA_real_,
      flags = list(vector_priors = TRUE),
      note = "Multivariate Cauchy prior fixture with two monitored coordinates."
    ),
    list(
      model_name = "fit_vector_mt",
      profile = "fixture",
      has_marglik = FALSE,
      model_family = "prior-only-vector",
      formula = NA_character_,
      scale_policy = "none",
      prior_features = "vector",
      expected_monitor = paste0("p1[", 1:2, "]"),
      expected_formula_parameters = character(),
      expected_formula_scale = character(),
      oracle_type = "fixture-metadata",
      expected_chains = 2L,
      expected_iterations = 500L,
      tolerance = NA_real_,
      flags = list(vector_priors = TRUE),
      note = "Multivariate t prior fixture with two monitored coordinates."
    ),
    list(
      model_name = "fit_factor_orthonormal",
      profile = "fixture",
      has_marglik = FALSE,
      model_family = "prior-only-factor",
      formula = NA_character_,
      scale_policy = "none",
      prior_features = "factor",
      expected_monitor = paste0("p1[", 1:2, "]"),
      expected_formula_parameters = character(),
      expected_formula_scale = character(),
      oracle_type = "fixture-metadata",
      expected_chains = 2L,
      expected_iterations = 500L,
      tolerance = NA_real_,
      flags = list(factor_priors = TRUE),
      note = "Orthonormal factor prior fixture with two contrast coordinates."
    ),
    list(
      model_name = "fit_factor_treatment",
      profile = "fixture",
      has_marglik = FALSE,
      model_family = "prior-only-factor",
      formula = NA_character_,
      scale_policy = "none",
      prior_features = "factor",
      expected_monitor = "p1",
      expected_formula_parameters = character(),
      expected_formula_scale = character(),
      oracle_type = "fixture-metadata",
      expected_chains = 2L,
      expected_iterations = 500L,
      tolerance = NA_real_,
      flags = list(factor_priors = TRUE),
      note = "Two-level treatment factor prior fixture with one monitored coefficient."
    ),
    list(
      model_name = "fit_factor_independent",
      profile = "fixture",
      has_marglik = FALSE,
      model_family = "prior-only-factor",
      formula = NA_character_,
      scale_policy = "none",
      prior_features = "factor",
      expected_monitor = paste0("p1[", 1:3, "]"),
      expected_formula_parameters = character(),
      expected_formula_scale = character(),
      oracle_type = "fixture-metadata",
      expected_chains = 2L,
      expected_iterations = 500L,
      tolerance = NA_real_,
      flags = list(factor_priors = TRUE),
      note = "Independent factor prior fixture with one monitored coordinate per level."
    ),
    list(
      model_name = "fit_factor_meandif",
      profile = "fixture",
      has_marglik = FALSE,
      model_family = "prior-only-factor",
      formula = NA_character_,
      scale_policy = "none",
      prior_features = "factor",
      expected_monitor = paste0("p1[", 1:2, "]"),
      expected_formula_parameters = character(),
      expected_formula_scale = character(),
      oracle_type = "fixture-metadata",
      expected_chains = 2L,
      expected_iterations = 500L,
      tolerance = NA_real_,
      flags = list(factor_priors = TRUE),
      note = "Mean-difference factor prior fixture with two monitored contrasts."
    ),
    list(
      model_name = "fit_formula_simple",
      profile = "fixture",
      has_marglik = TRUE,
      model_family = "gaussian-regression",
      formula = "~ x_cont1",
      scale_policy = "none",
      prior_features = "simple,formula",
      expected_monitor = c("mu_intercept", "mu_x_cont1", "sigma"),
      expected_formula_parameters = "mu",
      expected_formula_scale = character(),
      oracle_type = "formula-fixture-metadata",
      expected_chains = 2L,
      expected_iterations = 500L,
      tolerance = NA_real_,
      flags = list(simple_priors = TRUE, formulas = TRUE),
      note = "Simple formula regression fixture with bridge marginal likelihood."
    ),
    list(
      model_name = "fit_formula_treatment",
      profile = "fixture",
      has_marglik = TRUE,
      model_family = "gaussian-regression",
      formula = "~ x_cont1 + x_fac2t",
      scale_policy = "none",
      prior_features = "simple,formula,factor",
      expected_monitor = c("mu_intercept", "mu_x_cont1", "mu_x_fac2t", "sigma"),
      expected_formula_parameters = "mu",
      expected_formula_scale = character(),
      oracle_type = "formula-fixture-metadata",
      expected_chains = 2L,
      expected_iterations = 500L,
      tolerance = NA_real_,
      flags = list(simple_priors = TRUE, factor_priors = TRUE, formulas = TRUE),
      note = "Formula regression fixture with continuous predictor and two-level treatment factor."
    ),
    list(
      model_name = "fit_formula_orthonormal",
      profile = "fixture",
      has_marglik = TRUE,
      model_family = "gaussian-regression",
      formula = "~ x_cont1 + x_fac3o",
      scale_policy = "none",
      prior_features = "simple,formula,factor",
      expected_monitor = c("mu_intercept", "mu_x_cont1", "mu_x_fac3o[1]", "mu_x_fac3o[2]", "sigma"),
      expected_formula_parameters = "mu",
      expected_formula_scale = character(),
      oracle_type = "formula-fixture-metadata",
      expected_chains = 2L,
      expected_iterations = 500L,
      tolerance = NA_real_,
      flags = list(simple_priors = TRUE, factor_priors = TRUE, formulas = TRUE),
      note = "Formula regression fixture with continuous predictor and three-level orthonormal factor."
    ),
    list(
      model_name = "fit_formula_interaction_cont",
      profile = "fixture",
      has_marglik = FALSE,
      model_family = "gaussian-regression",
      formula = "~ x_cont1 * x_cont2",
      scale_policy = "none",
      prior_features = "simple,formula,interaction",
      expected_monitor = c(
        "mu_intercept",
        "mu_x_cont1",
        "mu_x_cont2",
        "mu_x_cont1__xXx__x_cont2",
        "sigma"
      ),
      expected_formula_parameters = "mu",
      expected_formula_scale = character(),
      oracle_type = "formula-fixture-metadata",
      expected_chains = 2L,
      expected_iterations = 500L,
      tolerance = NA_real_,
      flags = list(simple_priors = TRUE, formulas = TRUE, interactions = TRUE),
      note = "Continuous-by-continuous formula interaction fixture."
    ),
    list(
      model_name = "fit_formula_manual_scaled",
      profile = "fixture",
      has_marglik = FALSE,
      model_family = "gaussian-regression",
      formula = "~ x_cont1 * x_cont2",
      scale_policy = "manual",
      prior_features = "simple,formula,interaction",
      expected_monitor = c(
        "mu_intercept",
        "mu_x_cont1",
        "mu_x_cont2",
        "mu_x_cont1__xXx__x_cont2",
        "sigma"
      ),
      expected_formula_parameters = "mu",
      expected_formula_scale = character(),
      oracle_type = "formula-scale-fixture-metadata",
      expected_chains = 2L,
      expected_iterations = 500L,
      tolerance = 1e-10,
      flags = list(simple_priors = TRUE, formulas = TRUE, interactions = TRUE),
      note = "Manual standardized interaction regression fixture."
    ),
    list(
      model_name = "fit_formula_auto_scaled",
      profile = "fixture",
      has_marglik = FALSE,
      model_family = "gaussian-regression",
      formula = "~ x_cont1 * x_cont2",
      scale_policy = "automatic",
      prior_features = "simple,formula,interaction,formula_scale",
      expected_monitor = c(
        "mu_intercept",
        "mu_x_cont1",
        "mu_x_cont2",
        "mu_x_cont1__xXx__x_cont2",
        "sigma"
      ),
      expected_formula_parameters = "mu",
      expected_formula_scale = c("mu_x_cont1", "mu_x_cont2"),
      oracle_type = "formula-scale-fixture-metadata",
      expected_chains = 2L,
      expected_iterations = 500L,
      tolerance = 1e-10,
      flags = list(simple_priors = TRUE, formulas = TRUE, interactions = TRUE),
      note = "Automatically standardized interaction regression fixture."
    ),
    list(
      model_name = "fit_formula_interaction_mix",
      profile = "fixture",
      has_marglik = FALSE,
      model_family = "gaussian-regression",
      formula = "~ x_cont1 * x_fac3o",
      scale_policy = "none",
      prior_features = "simple,formula,factor,interaction",
      expected_monitor = c(
        "mu_intercept",
        "mu_x_cont1",
        "mu_x_fac3o[1]",
        "mu_x_fac3o[2]",
        "mu_x_cont1__xXx__x_fac3o[1]",
        "mu_x_cont1__xXx__x_fac3o[2]",
        "sigma"
      ),
      expected_formula_parameters = "mu",
      expected_formula_scale = character(),
      oracle_type = "formula-fixture-metadata",
      expected_chains = 2L,
      expected_iterations = 500L,
      tolerance = NA_real_,
      flags = list(simple_priors = TRUE, factor_priors = TRUE, formulas = TRUE, interactions = TRUE),
      note = "Continuous-by-orthonormal-factor formula interaction fixture."
    ),
    list(
      model_name = "fit_formula_interaction_mix_main",
      profile = "fixture",
      has_marglik = FALSE,
      model_family = "gaussian-regression",
      formula = "~ x_cont1 + x_fac3o",
      scale_policy = "none",
      prior_features = "simple,formula,factor",
      expected_monitor = c(
        "mu_intercept",
        "mu_x_cont1",
        "mu_x_fac3o[1]",
        "mu_x_fac3o[2]",
        "sigma"
      ),
      expected_formula_parameters = "mu",
      expected_formula_scale = character(),
      oracle_type = "formula-fixture-metadata",
      expected_chains = 2L,
      expected_iterations = 500L,
      tolerance = NA_real_,
      flags = list(simple_priors = TRUE, factor_priors = TRUE, formulas = TRUE),
      note = "Continuous plus orthonormal-factor main-effects fixture paired with interaction tests."
    ),
    list(
      model_name = "fit_formula_interaction_fac",
      profile = "fixture",
      has_marglik = FALSE,
      model_family = "gaussian-regression",
      formula = "~ x_fac2t * x_fac3o",
      scale_policy = "none",
      prior_features = "simple,formula,factor,interaction",
      expected_monitor = c(
        "mu_intercept",
        "mu_x_fac2t",
        "mu_x_fac3o[1]",
        "mu_x_fac3o[2]",
        "mu_x_fac2t__xXx__x_fac3o[1]",
        "mu_x_fac2t__xXx__x_fac3o[2]",
        "sigma"
      ),
      expected_formula_parameters = "mu",
      expected_formula_scale = character(),
      oracle_type = "formula-fixture-metadata",
      expected_chains = 2L,
      expected_iterations = 500L,
      tolerance = NA_real_,
      flags = list(simple_priors = TRUE, factor_priors = TRUE, formulas = TRUE, interactions = TRUE),
      note = "Treatment-by-orthonormal-factor formula interaction fixture."
    ),
    list(
      model_name = "fit_formula_factor_mixture",
      profile = "fixture",
      has_marglik = FALSE,
      model_family = "gaussian-regression",
      formula = "~ x_cont + x_fac3t",
      scale_policy = "mixture-indicator",
      prior_features = "simple,formula,factor,mixture",
      expected_monitor = c(
        "mu_intercept",
        "mu_x_cont",
        "mu_x_fac3t_indicator",
        "mu_x_fac3t[1]",
        "mu_x_fac3t[2]",
        "sigma"
      ),
      expected_formula_parameters = "mu",
      expected_formula_scale = character(),
      oracle_type = "formula-fixture-metadata",
      expected_chains = 2L,
      expected_iterations = 500L,
      tolerance = NA_real_,
      flags = list(simple_priors = TRUE, factor_priors = TRUE, formulas = TRUE, mixture_priors = TRUE),
      note = "Formula regression fixture with a mixture prior on a three-level treatment factor."
    ),
    list(
      model_name = "fit_formula_multi",
      profile = "fixture",
      has_marglik = FALSE,
      model_family = "gaussian-regression",
      formula = "mu: ~ x_cont1; sigma_exp: ~ x_fac2t",
      scale_policy = "multi-formula",
      prior_features = "simple,formula,factor,multi_formula",
      expected_monitor = c(
        "mu_intercept",
        "mu_x_cont1",
        "sigma_exp_x_fac2t",
        "sigma"
      ),
      expected_formula_parameters = c("mu", "sigma_exp"),
      expected_formula_scale = character(),
      oracle_type = "formula-fixture-metadata",
      expected_chains = 2L,
      expected_iterations = 500L,
      tolerance = NA_real_,
      flags = list(simple_priors = TRUE, factor_priors = TRUE, formulas = TRUE, multi_formula = TRUE),
      note = "Two-formula regression fixture for mean and multiplicative sigma expansion."
    ),
    list(
      model_name = "fit_mixture_simple",
      profile = "fixture",
      has_marglik = FALSE,
      model_family = "prior-only-mixture",
      formula = NA_character_,
      scale_policy = "mixture-indicator",
      prior_features = "mixture",
      expected_monitor = c("mu_indicator", "mu"),
      expected_formula_parameters = character(),
      expected_formula_scale = character(),
      oracle_type = "fixture-metadata",
      expected_chains = 2L,
      expected_iterations = 500L,
      tolerance = NA_real_,
      flags = list(mixture_priors = TRUE),
      note = "Scalar mixture prior fixture with monitored component indicator."
    ),
    list(
      model_name = "fit_mixture_components",
      profile = "fixture",
      has_marglik = FALSE,
      model_family = "prior-only-mixture",
      formula = NA_character_,
      scale_policy = "mixture-indicator",
      prior_features = "mixture",
      expected_monitor = c("beta_indicator", "beta"),
      expected_formula_parameters = character(),
      expected_formula_scale = character(),
      oracle_type = "fixture-metadata",
      expected_chains = 2L,
      expected_iterations = 500L,
      tolerance = NA_real_,
      flags = list(mixture_priors = TRUE),
      note = "Named-components mixture prior fixture with monitored indicator."
    ),
    list(
      model_name = "fit_mixture_spike",
      profile = "fixture",
      has_marglik = FALSE,
      model_family = "prior-only-mixture",
      formula = NA_character_,
      scale_policy = "mixture-indicator",
      prior_features = "mixture,point",
      expected_monitor = c("gamma_indicator", "gamma"),
      expected_formula_parameters = character(),
      expected_formula_scale = character(),
      oracle_type = "fixture-metadata",
      expected_chains = 2L,
      expected_iterations = 500L,
      tolerance = NA_real_,
      flags = list(mixture_priors = TRUE),
      note = "Mixture prior fixture with spike component and monitored indicator."
    ),
    list(
      model_name = "fit_expression_simple",
      profile = "fixture",
      has_marglik = FALSE,
      model_family = "prior-only-expression",
      formula = NA_character_,
      scale_policy = "expression-linked",
      prior_features = "simple,expression",
      expected_monitor = c("x", "x_sigma", "inv_x_sigma"),
      expected_formula_parameters = character(),
      expected_formula_scale = character(),
      oracle_type = "fixture-metadata",
      expected_chains = 2L,
      expected_iterations = 500L,
      tolerance = NA_real_,
      flags = list(simple_priors = TRUE, expression_priors = TRUE),
      note = "Expression prior fixture with monitored hyperparameter and inverse scale."
    ),
    list(
      model_name = "fit_expression_mixture",
      profile = "fixture",
      has_marglik = FALSE,
      model_family = "prior-only-expression",
      formula = NA_character_,
      scale_policy = "expression-linked,mixture-indicator",
      prior_features = "simple,mixture,expression",
      expected_monitor = c("x_indicator", "x", "x_sigma", "inv_x_sigma"),
      expected_formula_parameters = character(),
      expected_formula_scale = character(),
      oracle_type = "fixture-metadata",
      expected_chains = 2L,
      expected_iterations = 500L,
      tolerance = NA_real_,
      flags = list(simple_priors = TRUE, mixture_priors = TRUE, expression_priors = TRUE),
      note = "Expression mixture fixture with monitored component indicator and inverse scale."
    ),
    list(
      model_name = "fit_add_parameters",
      profile = "fixture",
      has_marglik = FALSE,
      model_family = "normal-location-scale",
      formula = NA_character_,
      scale_policy = "additional-monitor",
      prior_features = "simple,add-parameters",
      expected_monitor = c("m", "s", "g"),
      expected_formula_parameters = character(),
      expected_formula_scale = character(),
      oracle_type = "fixture-metadata",
      expected_chains = 2L,
      expected_iterations = 300L,
      tolerance = NA_real_,
      flags = list(simple_priors = TRUE, add_parameters = TRUE),
      note = "Location-scale fixture with explicit additional monitored parameter."
    ),
    list(
      model_name = "fit_parallel",
      profile = "fixture",
      has_marglik = FALSE,
      model_family = "normal-location-scale",
      formula = NA_character_,
      scale_policy = "parallel-chains",
      prior_features = "simple,parallel",
      expected_monitor = c("m", "s"),
      expected_formula_parameters = character(),
      expected_formula_scale = character(),
      oracle_type = "fixture-metadata",
      expected_chains = 2L,
      expected_iterations = 300L,
      tolerance = NA_real_,
      flags = list(simple_priors = TRUE, parallel = TRUE),
      note = "Location-scale fixture fitted with parallel chains."
    )
  )

  catalog_rows <- c(catalog_rows, list(
    catalog_row(
      "fit_weightfunction_onesided2",
      has_marglik = FALSE,
      model_family = "prior-only-weightfunction",
      scale_policy = "weightfunction-cumulative",
      prior_features = "weightfunction",
      expected_monitor = c("omega[1]", "omega[2]", "eta[1]", "eta[2]"),
      expected_chains = 2L,
      expected_iterations = 500L,
      flags = list(weightfunction_priors = TRUE),
      note = "One-sided two-interval weightfunction fixture."
    ),
    catalog_row(
      "fit_weightfunction_onesided3",
      has_marglik = FALSE,
      model_family = "prior-only-weightfunction",
      scale_policy = "weightfunction-cumulative",
      prior_features = "weightfunction",
      expected_monitor = c("omega[1]", "omega[2]", "omega[3]", "eta[1]", "eta[2]", "eta[3]"),
      expected_chains = 2L,
      expected_iterations = 500L,
      flags = list(weightfunction_priors = TRUE),
      note = "One-sided three-interval weightfunction fixture."
    ),
    catalog_row(
      "fit_weightfunction_twosided",
      has_marglik = FALSE,
      model_family = "prior-only-weightfunction",
      scale_policy = "weightfunction-cumulative",
      prior_features = "weightfunction",
      expected_monitor = c("omega[1]", "omega[2]", "omega[3]", "eta[1]", "eta[2]"),
      expected_chains = 2L,
      expected_iterations = 500L,
      flags = list(weightfunction_priors = TRUE),
      note = "Two-sided weightfunction fixture."
    ),
    catalog_row(
      "fit_weightfunction_fixed",
      has_marglik = FALSE,
      model_family = "prior-only-weightfunction",
      scale_policy = "weightfunction-fixed",
      prior_features = "weightfunction,fixed",
      expected_monitor = c("omega[1]", "omega[2]"),
      expected_chains = 2L,
      expected_iterations = 500L,
      flags = list(weightfunction_priors = TRUE),
      note = "Fixed one-sided weightfunction fixture."
    ),
    catalog_row(
      "fit_wf_independent_gamma",
      has_marglik = FALSE,
      model_family = "prior-only-weightfunction",
      scale_policy = "weightfunction-independent",
      prior_features = "weightfunction,gamma",
      expected_monitor = c("omega[1]", "omega[2]"),
      expected_chains = 1L,
      expected_iterations = 300L,
      flags = list(weightfunction_priors = TRUE),
      note = "Independent gamma weightfunction fixture."
    ),
    catalog_row(
      "fit_wf_independent_log",
      has_marglik = FALSE,
      model_family = "prior-only-weightfunction",
      scale_policy = "weightfunction-independent-log",
      prior_features = "weightfunction,log_omega",
      expected_monitor = c("omega[1]", "omega[2]", "log_omega[2]"),
      expected_chains = 1L,
      expected_iterations = 300L,
      flags = list(weightfunction_priors = TRUE),
      note = "Independent log-omega weightfunction fixture."
    ),
    catalog_row(
      "fit_bias_heterogeneous_wf",
      has_marglik = FALSE,
      model_family = "prior-only-publication-bias-mixture",
      scale_policy = "mixture-indicator,weightfunction",
      prior_features = "publication-bias,weightfunction,mixture",
      expected_monitor = c("bias_indicator", paste0("omega[", 1:5, "]")),
      expected_chains = 1L,
      expected_iterations = 1000L,
      flags = list(pub_bias_priors = TRUE, weightfunction_priors = TRUE, mixture_priors = TRUE),
      note = "Heterogeneous publication-bias mixture with five omega monitors."
    ),
    catalog_row(
      "fit_bias_petpeese_heterogeneous_wf",
      has_marglik = FALSE,
      model_family = "prior-only-publication-bias-mixture",
      scale_policy = "mixture-indicator,weightfunction",
      prior_features = "publication-bias,weightfunction,mixture,PET,PEESE",
      expected_monitor = c("bias_indicator", paste0("omega[", 1:5, "]"), "PET", "PEESE"),
      expected_chains = 1L,
      expected_iterations = 1200L,
      flags = list(pub_bias_priors = TRUE, weightfunction_priors = TRUE, mixture_priors = TRUE),
      note = "Heterogeneous publication-bias mixture with PET, PEESE, and five omega monitors."
    ),
    catalog_row(
      "fit_selection_kernel_summary",
      has_marglik = FALSE,
      model_family = "normal-location-selection-kernel",
      scale_policy = "mixture-indicator,selection-kernel",
      prior_features = "simple,publication-bias,weightfunction,mixture,selection-kernel",
      expected_monitor = c("mu_indicator", "mu", "bias_indicator", "omega[1]", "omega[2]", "alpha", "phack_kind", "pi_null"),
      expected_chains = 1L,
      expected_iterations = 100L,
      flags = list(simple_priors = TRUE, pub_bias_priors = TRUE, weightfunction_priors = TRUE, mixture_priors = TRUE),
      note = "Selection-kernel summary fixture with ordinary and publication-bias mixtures."
    ),
    catalog_row(
      "fit_spike_slab_simple",
      has_marglik = FALSE,
      model_family = "prior-only-spike-and-slab",
      scale_policy = "spike-and-slab-indicator",
      prior_features = "spike-and-slab",
      expected_monitor = c("mu_indicator", "mu_inclusion", "mu", "mu_variable"),
      expected_chains = 2L,
      expected_iterations = 500L,
      flags = list(spike_and_slab_priors = TRUE),
      note = "Scalar spike-and-slab fixture with inclusion and variable monitors."
    ),
    catalog_row(
      "fit_spike_slab_factor",
      has_marglik = FALSE,
      model_family = "prior-only-factor-spike-and-slab",
      scale_policy = "spike-and-slab-indicator",
      prior_features = "factor,spike-and-slab",
      expected_monitor = c("beta_indicator", "beta_inclusion", "beta[1]", "beta[2]", "beta_variable[1]", "beta_variable[2]"),
      expected_chains = 2L,
      expected_iterations = 500L,
      flags = list(factor_priors = TRUE, spike_and_slab_priors = TRUE),
      note = "Orthonormal factor spike-and-slab fixture."
    ),
    catalog_row(
      "fit_random_intercept",
      has_marglik = FALSE,
      model_family = "gaussian-regression-random-effects",
      formula = "~ 1 + (1 || id)",
      scale_policy = "random-effects",
      prior_features = "simple,formula,random-effects",
      expected_monitor = c(
        "mu_intercept", "mu__xREx__id_intercept", "sigma",
        .bayestools_random_z_monitors("mu__xREx__id_xRE_Zx", 10L, 1L)
      ),
      expected_formula_parameters = "mu",
      oracle_type = "formula-fixture-metadata",
      expected_chains = 2L,
      expected_iterations = 500L,
      flags = list(simple_priors = TRUE, formulas = TRUE, random_effects = TRUE),
      note = "Random-intercept regression fixture."
    ),
    catalog_row(
      "fit_random_slope",
      has_marglik = FALSE,
      model_family = "gaussian-regression-random-effects",
      formula = "~ 1 + (0 + x_cont1 || id)",
      scale_policy = "random-effects",
      prior_features = "simple,formula,random-effects",
      expected_monitor = c(
        "mu_intercept", "mu__xREx__id_x_cont1", "sigma",
        .bayestools_random_z_monitors("mu__xREx__id_xRE_Zx", 10L, 1L)
      ),
      expected_formula_parameters = "mu",
      oracle_type = "formula-fixture-metadata",
      expected_chains = 2L,
      expected_iterations = 500L,
      flags = list(simple_priors = TRUE, formulas = TRUE, random_effects = TRUE),
      note = "Random continuous-slope regression fixture."
    ),
    catalog_row(
      "fit_random_factor_slope",
      has_marglik = FALSE,
      model_family = "gaussian-regression-random-effects",
      formula = "~ 1 + x_cont1 + (x_fac3 || id)",
      scale_policy = "random-effects",
      prior_features = "simple,formula,factor,random-effects",
      expected_monitor = c(
        "mu_intercept", "mu_x_cont1", "mu__xREx__id_intercept",
        "mu__xREx__id_x_fac3[1]", "mu__xREx__id_x_fac3[2]", "sigma",
        .bayestools_random_z_monitors("mu__xREx__id_xRE_Zx", 10L, 3L)
      ),
      expected_formula_parameters = "mu",
      oracle_type = "formula-fixture-metadata",
      expected_chains = 2L,
      expected_iterations = 500L,
      flags = list(simple_priors = TRUE, factor_priors = TRUE, formulas = TRUE, random_effects = TRUE),
      note = "Random factor-slope regression fixture with fixed continuous effect."
    ),
    catalog_row(
      "fit_random_factor_slope2",
      has_marglik = FALSE,
      model_family = "gaussian-regression-random-effects",
      formula = "~ 1 + x_fac3 + (x_fac3 || id)",
      scale_policy = "random-effects",
      prior_features = "simple,formula,factor,random-effects",
      expected_monitor = c(
        "mu_intercept", "mu_x_fac3[1]", "mu_x_fac3[2]",
        "mu__xREx__id_intercept", "mu__xREx__id_x_fac3", "sigma",
        .bayestools_random_z_monitors("mu__xREx__id_xRE_Zx", 10L, 3L)
      ),
      expected_formula_parameters = "mu",
      oracle_type = "formula-fixture-metadata",
      expected_chains = 2L,
      expected_iterations = 500L,
      flags = list(simple_priors = TRUE, factor_priors = TRUE, formulas = TRUE, random_effects = TRUE),
      note = "Random factor-slope regression fixture with fixed orthonormal factor."
    ),
    catalog_row(
      "fit_random_factor_slope3",
      has_marglik = FALSE,
      model_family = "gaussian-regression-random-effects",
      formula = "~ -1 + x_fac3 + (x_fac3 - 1 || id)",
      scale_policy = "random-effects,spike-and-slab-indicator",
      prior_features = "simple,formula,factor,random-effects,spike-and-slab",
      expected_monitor = c(
        "mu_x_fac3[1]", "mu_x_fac3[2]", "mu_x_fac3[3]",
        "mu__xREx__id_x_fac3_indicator",
        "mu__xREx__id_x_fac3[1]", "mu__xREx__id_x_fac3[2]", "mu__xREx__id_x_fac3[3]",
        "mu__xREx__id_x_fac3_variable[1]", "mu__xREx__id_x_fac3_variable[2]", "mu__xREx__id_x_fac3_variable[3]",
        "sigma",
        .bayestools_random_z_monitors("mu__xREx__id_xRE_Zx", 10L, 3L)
      ),
      expected_formula_parameters = "mu",
      oracle_type = "formula-fixture-metadata",
      expected_chains = 2L,
      expected_iterations = 500L,
      flags = list(simple_priors = TRUE, factor_priors = TRUE, formulas = TRUE, random_effects = TRUE),
      note = "Independent-factor random slope fixture with spike-and-slab random effects."
    ),
    catalog_row(
      "fit_spike_factors",
      has_marglik = FALSE,
      model_family = "gaussian-regression",
      formula = "~ x_fac2i + x_fac3o + x_fac3t + x_fac3md - 1",
      scale_policy = "point-prior-fixed",
      prior_features = "formula,factor,point",
      expected_monitor = "sigma",
      expected_formula_parameters = "mu",
      oracle_type = "formula-fixture-metadata",
      expected_chains = 2L,
      expected_iterations = 500L,
      flags = list(factor_priors = TRUE, formulas = TRUE),
      note = "Formula fixture whose factor effects are all deterministic spike priors."
    ),
    catalog_row(
      "fit_joint_complex",
      has_marglik = FALSE,
      model_family = "gaussian-regression",
      formula = "~ x_cont1 + x_fac3t",
      scale_policy = "mixture-indicator,spike-and-slab-indicator,multiply-by",
      prior_features = "simple,formula,factor,mixture,spike-and-slab",
      expected_monitor = c(
        "mu_intercept_indicator", "mu_intercept",
        "mu_x_cont1_indicator", "mu_x_cont1",
        "mu_x_fac3t_indicator", "mu_x_fac3t[1]", "mu_x_fac3t[2]",
        "mu_x_fac3t_variable[1]", "mu_x_fac3t_variable[2]",
        "sigma_indicator", "sigma"
      ),
      expected_formula_parameters = "mu",
      oracle_type = "formula-fixture-metadata",
      expected_chains = 2L,
      expected_iterations = 500L,
      flags = list(
        simple_priors = TRUE, factor_priors = TRUE, spike_and_slab_priors = TRUE,
        mixture_priors = TRUE, formulas = TRUE
      ),
      note = "Joint formula fixture with mixture intercept, continuous mixture, factor spike-and-slab, and sigma mixture."
    ),
    catalog_row(
      "fit_expression_spike_slab",
      has_marglik = FALSE,
      model_family = "prior-only-expression",
      scale_policy = "expression-linked,spike-and-slab-indicator",
      prior_features = "simple,expression,spike-and-slab",
      expected_monitor = c("x_indicator", "x", "x_variable", "x_sigma", "inv_x_sigma"),
      expected_chains = 2L,
      expected_iterations = 500L,
      flags = list(simple_priors = TRUE, spike_and_slab_priors = TRUE, expression_priors = TRUE),
      note = "Expression prior fixture with a spike-and-slab alternative."
    ),
    catalog_row(
      "fit_no_autofit",
      has_marglik = FALSE,
      model_family = "normal-location",
      scale_policy = "no-autofit",
      prior_features = "simple",
      expected_monitor = "m",
      expected_chains = 2L,
      expected_iterations = 100L,
      flags = list(simple_priors = TRUE),
      note = "Poor-convergence location fixture without autofit."
    ),
    catalog_row(
      "fit_autofit_error",
      has_marglik = FALSE,
      model_family = "normal-location",
      scale_policy = "autofit-max-error",
      prior_features = "simple,autofit",
      expected_monitor = "m",
      expected_chains = 2L,
      expected_iterations = 300L,
      flags = list(simple_priors = TRUE, autofit = TRUE),
      note = "Autofit location fixture extended to satisfy max-error control."
    ),
    catalog_row(
      "fit_autofit_ess",
      has_marglik = FALSE,
      model_family = "normal-location",
      scale_policy = "autofit-min-ess",
      prior_features = "simple,autofit",
      expected_monitor = "m",
      expected_chains = 2L,
      expected_iterations = 200L,
      flags = list(simple_priors = TRUE, autofit = TRUE),
      note = "Autofit location fixture extended to satisfy minimum ESS control."
    ),
    catalog_row(
      "fit_marginal_0",
      has_marglik = TRUE,
      model_family = "gaussian-regression",
      formula = "~ x_cont1 + x_fac2t + x_cont1 * x_fac3md",
      scale_policy = "point-prior-fixed,multiply-by",
      prior_features = "formula,factor,interaction,point",
      expected_monitor = c("mu_intercept", "mu_x_cont1", "sigma"),
      expected_formula_parameters = "mu",
      oracle_type = "formula-fixture-metadata",
      expected_chains = 2L,
      expected_iterations = 500L,
      flags = list(factor_priors = TRUE, formulas = TRUE, interactions = TRUE),
      note = "Marginal-inference null fixture with spike factor and interaction terms."
    ),
    catalog_row(
      "fit_marginal_1",
      has_marglik = TRUE,
      model_family = "gaussian-regression",
      formula = "~ x_cont1 + x_fac2t + x_cont1 * x_fac3md",
      scale_policy = "multiply-by",
      prior_features = "formula,factor,interaction",
      expected_monitor = c(
        "mu_intercept", "mu_x_cont1", "mu_x_fac2t",
        "mu_x_fac3md[1]", "mu_x_fac3md[2]",
        "mu_x_cont1__xXx__x_fac3md[1]", "mu_x_cont1__xXx__x_fac3md[2]",
        "sigma"
      ),
      expected_formula_parameters = "mu",
      oracle_type = "formula-fixture-metadata",
      expected_chains = 2L,
      expected_iterations = 500L,
      flags = list(factor_priors = TRUE, formulas = TRUE, interactions = TRUE),
      note = "Marginal-inference alternative fixture with factor and interaction effects."
    ),
    catalog_row(
      "fit_marginal_ss",
      has_marglik = FALSE,
      model_family = "gaussian-regression",
      formula = "~ x_cont1 + x_fac2t + x_cont1 * x_fac3md",
      scale_policy = "mixture-indicator,spike-and-slab-indicator,multiply-by",
      prior_features = "formula,factor,interaction,mixture,spike-and-slab",
      expected_monitor = c(
        "mu_intercept",
        "mu_x_cont1_indicator", "mu_x_cont1",
        "mu_x_fac2t_indicator", "mu_x_fac2t", "mu_x_fac2t_variable",
        "mu_x_fac3md_indicator", "mu_x_fac3md[1]", "mu_x_fac3md[2]",
        "mu_x_fac3md_variable[1]", "mu_x_fac3md_variable[2]",
        "mu_x_cont1__xXx__x_fac3md_indicator",
        "mu_x_cont1__xXx__x_fac3md[1]", "mu_x_cont1__xXx__x_fac3md[2]",
        "mu_x_cont1__xXx__x_fac3md_variable[1]", "mu_x_cont1__xXx__x_fac3md_variable[2]",
        "sigma"
      ),
      expected_formula_parameters = "mu",
      oracle_type = "formula-fixture-metadata",
      expected_chains = 2L,
      expected_iterations = 500L,
      flags = list(
        factor_priors = TRUE, spike_and_slab_priors = TRUE, mixture_priors = TRUE,
        formulas = TRUE, interactions = TRUE
      ),
      note = "Marginal-inference spike-and-slab fixture with mixture continuous effect."
    ),
    catalog_row(
      "fit_pet",
      has_marglik = TRUE,
      model_family = "prior-only-publication-bias",
      prior_features = "publication-bias,PET",
      expected_monitor = "PET",
      expected_chains = 1L,
      expected_iterations = 2000L,
      flags = list(pub_bias_priors = TRUE),
      note = "PET publication-bias fixture with bridge marginal likelihood."
    ),
    catalog_row(
      "fit_peese",
      has_marglik = TRUE,
      model_family = "prior-only-publication-bias",
      prior_features = "publication-bias,PEESE",
      expected_monitor = "PEESE",
      expected_chains = 1L,
      expected_iterations = 2000L,
      flags = list(pub_bias_priors = TRUE),
      note = "PEESE publication-bias fixture with bridge marginal likelihood."
    ),
    catalog_row(
      "fit_missing",
      has_marglik = TRUE,
      model_family = "prior-only-scalar",
      prior_features = "simple",
      expected_monitor = "mu",
      expected_chains = 1L,
      expected_iterations = 2000L,
      flags = list(simple_priors = TRUE),
      note = "Overwhelming missing-model scalar fixture with bridge marginal likelihood."
    ),
    catalog_row(
      "fit_wf_onesided",
      has_marglik = TRUE,
      model_family = "prior-only-weightfunction",
      scale_policy = "weightfunction-cumulative",
      prior_features = "weightfunction",
      expected_monitor = c("omega[1]", "omega[2]", "eta[1]", "eta[2]"),
      expected_chains = 1L,
      expected_iterations = 2000L,
      flags = list(weightfunction_priors = TRUE),
      note = "One-sided weightfunction fixture with bridge marginal likelihood."
    ),
    catalog_row(
      "fit_wf_twosided",
      has_marglik = TRUE,
      model_family = "prior-only-weightfunction",
      scale_policy = "weightfunction-cumulative",
      prior_features = "weightfunction",
      expected_monitor = c("omega[1]", "omega[2]", "omega[3]", "eta[1]", "eta[2]"),
      expected_chains = 1L,
      expected_iterations = 2000L,
      flags = list(weightfunction_priors = TRUE),
      note = "Two-sided weightfunction fixture with bridge marginal likelihood."
    ),
    catalog_row(
      "fit_wf_missing",
      has_marglik = TRUE,
      model_family = "prior-only-scalar",
      prior_features = "simple",
      expected_monitor = "mu",
      expected_chains = 1L,
      expected_iterations = 2000L,
      flags = list(simple_priors = TRUE),
      note = "Overwhelming missing-model weightfunction companion fixture with bridge marginal likelihood."
    ),
    catalog_row(
      "fit_orthonormal_0",
      has_marglik = TRUE,
      model_family = "gaussian-regression",
      formula = "~ 1",
      prior_features = "formula,factor",
      expected_monitor = c("mu_intercept", "sigma"),
      expected_formula_parameters = "mu",
      oracle_type = "formula-fixture-metadata",
      expected_chains = 4L,
      expected_iterations = 4000L,
      flags = list(factor_priors = TRUE, formulas = TRUE),
      note = "Orthonormal model-averaging null fixture with bridge marginal likelihood."
    ),
    catalog_row(
      "fit_orthonormal_1",
      has_marglik = TRUE,
      model_family = "gaussian-regression",
      formula = "~ x_fac3o",
      prior_features = "formula,factor",
      expected_monitor = c("mu_intercept", "mu_x_fac3o[1]", "mu_x_fac3o[2]", "sigma"),
      expected_formula_parameters = "mu",
      oracle_type = "formula-fixture-metadata",
      expected_chains = 4L,
      expected_iterations = 4000L,
      flags = list(factor_priors = TRUE, formulas = TRUE),
      note = "Orthonormal model-averaging alternative fixture with bridge marginal likelihood."
    ),
    catalog_row(
      "fit_complex_mixed",
      has_marglik = FALSE,
      model_family = "gaussian-regression-optional",
      formula = "~ x_cont1 + x_fac2t + x_fac3t",
      scale_policy = "mixture-indicator,spike-and-slab-indicator,multiply-by,weightfunction",
      prior_features = "formula,publication-bias,weightfunction,mixture,spike-and-slab",
      expected_monitor = c(
        "mu_intercept_indicator", "mu_intercept",
        "mu_x_cont1_indicator", "mu_x_cont1", "mu_x_cont1_variable",
        "mu_x_fac2t_indicator", "mu_x_fac2t",
        "mu_x_fac3t_indicator", "mu_x_fac3t[1]", "mu_x_fac3t[2]",
        "sigma_indicator", "sigma",
        "bias_indicator", "omega[1]", "omega[2]", "omega[3]", "omega[4]", "PET"
      ),
      expected_formula_parameters = "mu",
      oracle_type = "formula-fixture-metadata",
      expected_chains = 1L,
      expected_iterations = 500L,
      flags = list(
        pub_bias_priors = TRUE, weightfunction_priors = TRUE, spike_and_slab_priors = TRUE,
        mixture_priors = TRUE, formulas = TRUE
      ),
      note = "Optional complex plotting fixture with formula mixtures, sigma mixture, and publication bias."
    ),
    catalog_row(
      "fit_simple_formula_mixed",
      has_marglik = FALSE,
      model_family = "gaussian-regression-optional",
      formula = "~ x_cont1 + x_fac2t + x_fac3t",
      scale_policy = "multiply-by",
      prior_features = "simple,formula,factor",
      expected_monitor = c("mu_intercept", "mu_x_cont1", "mu_x_fac2t", "mu_x_fac3t[1]", "mu_x_fac3t[2]", "sigma"),
      expected_formula_parameters = "mu",
      oracle_type = "formula-fixture-metadata",
      expected_chains = 1L,
      expected_iterations = 500L,
      flags = list(simple_priors = TRUE, factor_priors = TRUE, formulas = TRUE),
      note = "Optional simple plotting fixture with continuous and factor formula effects."
    ),
    catalog_row(
      "fit_complex_bias",
      has_marglik = FALSE,
      model_family = "prior-only-publication-bias-optional",
      scale_policy = "mixture-indicator,weightfunction",
      prior_features = "publication-bias,weightfunction,mixture,PET,PEESE",
      expected_monitor = c("mu", "bias_indicator", "omega[1]", "omega[2]", "omega[3]", "omega[4]", "PET", "PEESE"),
      expected_chains = 1L,
      expected_iterations = 500L,
      flags = list(pub_bias_priors = TRUE, weightfunction_priors = TRUE, mixture_priors = TRUE),
      note = "Optional publication-bias plotting fixture with PET, PEESE, and weightfunction components."
    ),
    catalog_row(
      "fit_dual_param_regression",
      has_marglik = TRUE,
      model_family = "gaussian-dual-parameter-regression",
      formula = "mu: ~ x_mu; log_sigma: ~ x_sigma",
      scale_policy = "automatic,log-intercept",
      prior_features = "simple,formula,formula_scale",
      expected_monitor = c("mu_intercept", "mu_x_mu", "log_sigma_intercept", "log_sigma_x_sigma"),
      expected_formula_parameters = c("mu", "log_sigma"),
      expected_formula_scale = c(mu = "mu_x_mu", log_sigma = "log_sigma_x_sigma"),
      oracle_type = "formula-scale-fixture-metadata",
      expected_chains = 2L,
      expected_iterations = 500L,
      flags = list(simple_priors = TRUE, formulas = TRUE),
      tolerance = 1e-10,
      note = "Dual-parameter formula fixture with scaled mean and log-sigma predictors."
    )
  ))

  overrides <- do.call(rbind, lapply(catalog_rows, function(row) {
    flags <- as.list(rep(FALSE, length(flag_cols)))
    names(flags) <- flag_cols
    flags[names(row$flags)] <- row$flags

    data.frame(
      model_name = row$model_name,
      profile = row$profile,
      fit_file = paste0(row$model_name, ".RDS"),
      marglik_file = if (isTRUE(row$has_marglik)) paste0(row$model_name, ".RDS") else NA_character_,
      has_marglik = row$has_marglik,
      as.data.frame(flags, check.names = FALSE),
      model_family = row$model_family,
      formula = row$formula,
      scale_policy = row$scale_policy,
      prior_features = row$prior_features,
      oracle_type = row$oracle_type,
      expected_chains = row$expected_chains,
      expected_iterations = row$expected_iterations,
      expected_parameter_count = length(row$expected_monitor),
      tolerance = row$tolerance,
      note = row$note,
      stringsAsFactors = FALSE,
      check.names = FALSE
    )
  }))

  overrides$expected_monitor <- I(lapply(catalog_rows, `[[`, "expected_monitor"))
  overrides$expected_formula_parameters <- I(lapply(catalog_rows, `[[`, "expected_formula_parameters"))
  overrides$expected_formula_scale <- I(lapply(catalog_rows, `[[`, "expected_formula_scale"))
  rownames(overrides) <- NULL
  overrides
}

bayestools_expected_fit_catalog <- function() {
  catalog <- .bayestools_save_fit_catalog_rows()
  overrides <- bayestools_semantic_fit_catalog_overrides()

  missing_overrides <- setdiff(overrides$model_name, catalog$model_name)
  if (length(missing_overrides) > 0L) {
    stop(
      "Semantic fit catalog overrides are not generated by test-00-model-fits.R: ",
      paste(missing_overrides, collapse = ", "),
      call. = FALSE
    )
  }

  for (model_name in overrides$model_name) {
    catalog_index <- match(model_name, catalog$model_name)
    override_index <- match(model_name, overrides$model_name)

    for (column in setdiff(names(overrides), "note")) {
      catalog[[column]][catalog_index] <- overrides[[column]][override_index]
    }
  }

  rownames(catalog) <- NULL
  catalog
}

bayestools_fit_catalog_available <- function(catalog = bayestools_expected_fit_catalog()) {
  vapply(catalog$requires_package, function(package) {
    is.na(package) || requireNamespace(package, quietly = TRUE)
  }, logical(1))
}

bayestools_required_fit_catalog <- function(catalog = bayestools_expected_fit_catalog()) {
  catalog[bayestools_fit_catalog_available(catalog), , drop = FALSE]
}

.bayestools_catalog_row <- function(catalog, model_name) {
  row_index <- match(model_name, catalog$model_name)
  if (is.na(row_index)) {
    stop("Model '", model_name, "' is not in the expected fit catalog.", call. = FALSE)
  }
  catalog[row_index, , drop = FALSE]
}

expect_registry_schema <- function(registry) {
  testthat::expect_s3_class(registry, "data.frame")

  required_columns <- bayestools_registry_schema_columns()
  missing_columns <- setdiff(required_columns, names(registry))
  testthat::expect_equal(
    length(missing_columns),
    0L
  )
  extra_columns <- setdiff(names(registry), required_columns)
  testthat::expect_equal(
    length(extra_columns),
    0L
  )

  testthat::expect_false(anyDuplicated(registry$model_name) > 0L)
  testthat::expect_type(registry$model_name, "character")
  testthat::expect_false(anyNA(registry$model_name))
  testthat::expect_true(all(nzchar(registry$model_name)))
  testthat::expect_type(registry$note, "character")
  testthat::expect_false(anyNA(registry$note))
  testthat::expect_true(all(nzchar(registry$note)))
  for (flag in c("has_marglik", bayestools_registry_flag_columns())) {
    testthat::expect_type(registry[[flag]], "logical")
    testthat::expect_false(anyNA(registry[[flag]]))
  }

  invisible(registry)
}

expect_registry_matches_expected_catalog <- function(registry, catalog = bayestools_expected_fit_catalog()) {
  expect_registry_schema(registry)
  catalog <- bayestools_required_fit_catalog(catalog)

  missing_models <- setdiff(catalog$model_name, registry$model_name)
  testthat::expect_equal(
    length(missing_models),
    0L
  )
  extra_models <- setdiff(registry$model_name, catalog$model_name)
  testthat::expect_equal(
    length(extra_models),
    0L
  )

  for (model_name in catalog$model_name) {
    expected <- .bayestools_catalog_row(catalog, model_name)
    actual <- registry[match(model_name, registry$model_name), , drop = FALSE]

    for (flag in c("has_marglik", bayestools_registry_flag_columns())) {
      testthat::expect_identical(
        unname(actual[[flag]]),
        unname(expected[[flag]])
      )
    }
    testthat::expect_identical(
      unname(actual$note),
      unname(expected$note)
    )
  }

  invisible(registry)
}

expect_registry_artifact_policy <- function(registry) {
  expect_registry_schema(registry)

  expected_fit_files <- paste0(registry$model_name, ".RDS")
  actual_fit_files <- basename(list.files(temp_fits_dir, pattern = "\\.RDS$", full.names = FALSE))
  testthat::expect_setequal(
    actual_fit_files,
    expected_fit_files
  )

  expected_marglik_files <- paste0(registry$model_name[registry$has_marglik], ".RDS")
  actual_marglik_files <- basename(list.files(temp_marglik_dir, pattern = "\\.RDS$", full.names = FALSE))
  testthat::expect_setequal(
    actual_marglik_files,
    expected_marglik_files
  )

  invisible(TRUE)
}

expect_expected_fit_catalog_schema <- function(catalog) {
  testthat::expect_s3_class(catalog, "data.frame")

  required_columns <- c(
    "model_name", "profile", "fit_file", "marglik_file", "has_marglik",
    bayestools_registry_flag_columns(),
    "model_family", "formula", "scale_policy", "prior_features",
    "requires_package", "oracle_type", "expected_chains",
    "expected_iterations", "expected_parameter_count", "tolerance", "note",
    "expected_monitor", "expected_formula_parameters", "expected_formula_scale"
  )
  testthat::expect_setequal(names(catalog), required_columns)

  character_columns <- c(
    "model_name", "profile", "fit_file", "marglik_file", "model_family",
    "formula", "scale_policy", "prior_features", "requires_package",
    "oracle_type", "note"
  )
  for (column in character_columns) {
    testthat::expect_type(catalog[[column]], "character")
  }

  for (flag in c("has_marglik", bayestools_registry_flag_columns())) {
    testthat::expect_type(catalog[[flag]], "logical")
    testthat::expect_false(anyNA(catalog[[flag]]), info = flag)
  }

  testthat::expect_false(anyDuplicated(catalog$model_name) > 0L)
  testthat::expect_false(anyNA(catalog$model_name))
  testthat::expect_true(all(nzchar(catalog$model_name)))
  testthat::expect_false(anyNA(catalog$fit_file))
  testthat::expect_true(all(nzchar(catalog$fit_file)))
  testthat::expect_equal(catalog$fit_file, paste0(catalog$model_name, ".RDS"))
  testthat::expect_equal(is.na(catalog$marglik_file), !catalog$has_marglik)
  testthat::expect_equal(
    catalog$marglik_file[catalog$has_marglik],
    paste0(catalog$model_name[catalog$has_marglik], ".RDS")
  )
  testthat::expect_true(all(catalog$profile %in% bayestools_known_test_profiles))
  testthat::expect_true(all(nzchar(catalog$model_family)))
  testthat::expect_true(all(nzchar(catalog$scale_policy)))
  testthat::expect_true(all(nzchar(catalog$prior_features)))
  testthat::expect_true(all(nzchar(catalog$oracle_type)))
  testthat::expect_true(all(nzchar(catalog$note)))

  list_columns <- c("expected_monitor", "expected_formula_parameters", "expected_formula_scale")
  for (column in list_columns) {
    testthat::expect_true(is.list(catalog[[column]]), info = column)
    testthat::expect_equal(length(catalog[[column]]), nrow(catalog), info = column)
    testthat::expect_true(
      all(vapply(catalog[[column]], is.character, logical(1))),
      info = column
    )
  }

  semantic_rows <- vapply(catalog$expected_monitor, length, integer(1)) > 0L
  testthat::expect_true(all(semantic_rows))
  testthat::expect_false(any(catalog$oracle_type == "registry-metadata"))
  testthat::expect_equal(
    catalog$expected_parameter_count[semantic_rows],
    vapply(catalog$expected_monitor[semantic_rows], length, integer(1))
  )
  testthat::expect_true(all(is.na(catalog$expected_parameter_count[!semantic_rows])))

  invisible(catalog)
}

expect_cache_completion_marker <- function(name = "model-fit",
                                           catalog = bayestools_expected_fit_catalog()) {
  marker_file <- .test_cache_indicator_file(name)
  testthat::expect_true(file.exists(marker_file))

  marker <- .test_cache_marker_values(marker_file)
  marker_value <- function(key) {
    if (!key %in% names(marker)) {
      return(NA_character_)
    }
    unname(marker[[key]])
  }

  testthat::expect_identical(marker_value("name"), name)
  testthat::expect_false(is.na(marker_value("completed_at")))
  testthat::expect_false(is.na(marker_value("test_files_dir")))
  testthat::expect_equal(
    normalizePath(marker_value("test_files_dir"), winslash = "/", mustWork = TRUE),
    normalizePath(test_files_dir, winslash = "/", mustWork = TRUE)
  )

  catalog <- bayestools_required_fit_catalog(catalog)
  testthat::expect_identical(
    marker_value("required_fits"),
    .test_cache_name_line(catalog$model_name)
  )
  testthat::expect_identical(
    marker_value("required_margliks"),
    .test_cache_name_line(catalog$model_name[catalog$has_marglik])
  )

  registry_file <- file.path(test_files_dir, "model_registry.RDS")
  testthat::expect_true(file.exists(registry_file))
  testthat::expect_identical(
    marker_value("registry_md5"),
    .test_cache_file_md5(registry_file)
  )

  source_hashes <- .test_cache_source_hashes(name)
  testthat::expect_true(length(source_hashes) > 0L)
  for (source_name in names(source_hashes)) {
    testthat::expect_identical(
      marker_value(paste0("source_md5_", source_name)),
      unname(source_hashes[[source_name]]),
      info = paste("cache source hash:", source_name)
    )
  }

  testthat::expect_true(.test_cache_metadata_current(name, registry_file = registry_file))

  invisible(marker_file)
}

expect_fit_file_present <- function(model_name, catalog = bayestools_expected_fit_catalog()) {
  row <- .bayestools_catalog_row(catalog, model_name)
  path <- file.path(temp_fits_dir, row$fit_file)
  testthat::expect_true(file.exists(path))
  invisible(path)
}

expect_marglik_file_present_or_absent <- function(model_name, catalog = bayestools_expected_fit_catalog()) {
  row <- .bayestools_catalog_row(catalog, model_name)

  if (isTRUE(row$has_marglik)) {
    path <- file.path(temp_marglik_dir, row$marglik_file)
    testthat::expect_true(file.exists(path))
  } else {
    path <- file.path(temp_marglik_dir, paste0(model_name, ".RDS"))
    testthat::expect_false(file.exists(path))
  }

  invisible(path)
}

expect_marglik_object <- function(marglik) {
  testthat::expect_s3_class(marglik, "bridge")
  testthat::expect_true("logml" %in% names(marglik))
  testthat::expect_type(marglik$logml, "double")
  testthat::expect_length(marglik$logml, 1L)
  testthat::expect_true(is.finite(marglik$logml))
  invisible(marglik)
}

.bayestools_fit_mcmc_list <- function(fit) {
  samples <- fit[["mcmc"]]
  if (inherits(samples, "mcmc.list")) {
    return(samples)
  }
  if (inherits(samples, "mcmc")) {
    return(coda::mcmc.list(samples))
  }

  suppressWarnings(coda::as.mcmc.list(fit))
}

expect_fit_monitors <- function(fit, expected_monitor) {
  testthat::expect_s3_class(fit, "BayesTools_fit")
  testthat::expect_s3_class(fit, "runjags")

  samples <- .bayestools_fit_mcmc_list(fit)
  monitored_columns <- lapply(samples, function(chain) colnames(as.matrix(chain)))

  for (chain_columns in monitored_columns) {
    testthat::expect_equal(chain_columns, expected_monitor)
  }

  invisible(monitored_columns[[1L]])
}

.bayestools_expected_formula_scale_by_parameter <- function(expected_formula_scale,
                                                            default_parameter = "mu") {
  if (length(expected_formula_scale) == 0L) {
    return(list())
  }

  scale_names <- names(expected_formula_scale)
  if (is.null(scale_names) || all(!nzchar(scale_names))) {
    out <- list(unname(expected_formula_scale))
    names(out) <- default_parameter
    return(out)
  }

  if (any(is.na(scale_names) | !nzchar(scale_names))) {
    stop("Named expected_formula_scale entries must all declare a formula parameter.", call. = FALSE)
  }

  split(unname(expected_formula_scale), scale_names)
}

.bayestools_catalog_formula_map <- function(formula_text, expected_parameters) {
  if (length(expected_parameters) == 0L || is.na(formula_text) || !nzchar(formula_text)) {
    return(list())
  }

  parse_formula <- function(text) {
    formula <- stats::as.formula(trimws(text), env = emptyenv())
    formula <- BayesTools:::.remove_response(formula)
    formula <- BayesTools:::.remove_expressions(formula)
    formula <- BayesTools:::.remove_random_effects(formula)
    if (attr(stats::terms(formula), "intercept") == 0) {
      formula <- formula_add_intercept(formula)
    }
    environment(formula) <- emptyenv()
    formula
  }

  parts <- strsplit(formula_text, "\\s*;\\s*")[[1]]
  parts <- parts[nzchar(parts)]
  if (length(parts) == 1L && !grepl("^[[:alnum:]_.]+\\s*:", parts)) {
    out <- list(parse_formula(parts))
    names(out) <- expected_parameters[[1]]
    return(out)
  }

  out <- list()
  for (part in parts) {
    match <- regexec("^([[:alnum:]_.]+)\\s*:\\s*(.+)$", part)
    pieces <- regmatches(part, match)[[1]]
    if (length(pieces) != 3L) {
      stop("Could not parse catalog formula declaration: ", part, call. = FALSE)
    }
    out[[pieces[[2]]]] <- parse_formula(pieces[[3]])
  }
  out[names(out) %in% expected_parameters]
}

expect_fit_formula_metadata <- function(fit, expected_formula_parameters = character(),
                                        expected_formula_scale = character()) {
  formula_design <- attr(fit, "formula_design")

  if (length(expected_formula_parameters) > 0L) {
    testthat::expect_false(is.null(formula_design))
    testthat::expect_setequal(names(formula_design), expected_formula_parameters)
  } else {
    testthat::expect_null(formula_design)
  }

  formula_scale <- attr(fit, "formula_scale")
  if (length(expected_formula_scale) > 0L) {
    expected_scale <- .bayestools_expected_formula_scale_by_parameter(expected_formula_scale)
    testthat::expect_false(is.null(formula_scale))
    for (parameter in names(expected_scale)) {
      testthat::expect_true(parameter %in% names(formula_scale))
      testthat::expect_setequal(names(formula_scale[[parameter]]), expected_scale[[parameter]])
      for (term in expected_scale[[parameter]]) {
        testthat::expect_equal(names(formula_scale[[parameter]][[term]]), c("mean", "sd"))
        testthat::expect_true(is.finite(formula_scale[[parameter]][[term]]$mean))
        testthat::expect_true(is.finite(formula_scale[[parameter]][[term]]$sd))
        testthat::expect_gt(formula_scale[[parameter]][[term]]$sd, 0)
      }
    }
  } else {
    testthat::expect_null(formula_scale)
  }

  invisible(TRUE)
}

expect_fit_declared_metadata <- function(fit, row) {
  testthat::expect_s3_class(fit, "BayesTools_fit")
  testthat::expect_s3_class(fit, "runjags")

  fixture_metadata <- attr(fit, "fixture_metadata")
  testthat::expect_type(fixture_metadata, "list")
  testthat::expect_identical(fixture_metadata$schema_version, 1L)
  testthat::expect_identical(fixture_metadata$generated_by, "save_fit")
  testthat::expect_identical(fixture_metadata$cache_scope, "model-fit")
  testthat::expect_identical(fixture_metadata$model_name, unname(row$model_name))
  testthat::expect_identical(fixture_metadata$has_marglik, isTRUE(row$has_marglik))
  testthat::expect_identical(fixture_metadata$note, unname(row$note))

  testthat::expect_type(fixture_metadata$flags, "list")
  for (flag in bayestools_registry_flag_columns()) {
    testthat::expect_true(flag %in% names(fixture_metadata$flags))
    testthat::expect_identical(
      fixture_metadata$flags[[flag]],
      isTRUE(row[[flag]]),
      info = paste("fixture metadata flag:", row$model_name, flag)
    )
  }

  catalog_metadata <- fixture_metadata$catalog
  testthat::expect_type(catalog_metadata, "list")
  for (field in c("profile", "model_family", "formula", "scale_policy", "prior_features", "oracle_type")) {
    testthat::expect_identical(
      catalog_metadata[[field]],
      unname(row[[field]]),
      info = paste("fixture metadata catalog field:", row$model_name, field)
    )
  }
  testthat::expect_identical(as.integer(catalog_metadata$expected_chains), as.integer(row$expected_chains))
  testthat::expect_identical(as.integer(catalog_metadata$expected_iterations), as.integer(row$expected_iterations))
  testthat::expect_identical(
    as.integer(catalog_metadata$expected_parameter_count),
    as.integer(row$expected_parameter_count)
  )
  testthat::expect_equal(catalog_metadata$expected_monitor, row$expected_monitor[[1]])
  testthat::expect_equal(
    catalog_metadata$expected_formula_parameters,
    row$expected_formula_parameters[[1]]
  )
  testthat::expect_equal(catalog_metadata$expected_formula_scale, row$expected_formula_scale[[1]])

  prior_list <- attr(fit, "prior_list")
  testthat::expect_type(prior_list, "list")
  testthat::expect_false(anyDuplicated(names(prior_list)) > 0L)
  testthat::expect_true(all(nzchar(names(prior_list))))
  if (length(prior_list) > 0L && exists("is.prior", mode = "function")) {
    testthat::expect_true(all(vapply(prior_list, is.prior, logical(1))))
  }

  formula_design <- attr(fit, "formula_design")
  formula_expected <- isTRUE(row$formulas) ||
    isTRUE(row$multi_formula) ||
    isTRUE(row$random_effects)

  if (formula_expected) {
    testthat::expect_type(formula_design, "list")
    testthat::expect_true(all(nzchar(names(formula_design))))
    testthat::expect_true(
      all(vapply(formula_design, inherits, logical(1), "BayesTools_formula_design"))
    )

    formula_parameters <- unique(unlist(lapply(prior_list, attr, which = "parameter")))
    formula_parameters <- formula_parameters[!is.na(formula_parameters)]
    testthat::expect_true(all(formula_parameters %in% names(formula_design)))
  } else {
    testthat::expect_null(formula_design)
  }

  formula_scale <- attr(fit, "formula_scale")
  if (!is.null(formula_scale)) {
    testthat::expect_type(formula_scale, "list")
    testthat::expect_true(all(names(formula_scale) %in% names(formula_design)))
    for (parameter in names(formula_scale)) {
      testthat::expect_type(formula_scale[[parameter]], "list")
      for (term in names(formula_scale[[parameter]])) {
        scale_term <- formula_scale[[parameter]][[term]]
        testthat::expect_equal(names(scale_term), c("mean", "sd"))
        testthat::expect_true(is.finite(scale_term$mean))
        testthat::expect_true(is.finite(scale_term$sd))
        testthat::expect_gt(scale_term$sd, 0)
      }
    }
  }

  expected_formula_parameters <- row$expected_formula_parameters[[1]]
  if (length(expected_formula_parameters) > 0L) {
    testthat::expect_setequal(names(formula_design), expected_formula_parameters)

    expected_formula_map <- .bayestools_catalog_formula_map(row$formula, expected_formula_parameters)
    testthat::expect_setequal(names(expected_formula_map), expected_formula_parameters)
    for (parameter in names(expected_formula_map)) {
      testthat::expect_true(parameter %in% names(formula_design))
      testthat::expect_equal(
        as.character(formula_design[[parameter]]$formula),
        as.character(expected_formula_map[[parameter]]),
        info = paste("catalog formula:", row$model_name, parameter)
      )
    }
  }

  expected_formula_scale <- row$expected_formula_scale[[1]]
  if (length(expected_formula_scale) > 0L) {
    expected_scale <- .bayestools_expected_formula_scale_by_parameter(expected_formula_scale)
    testthat::expect_false(is.null(formula_scale))
    for (parameter in names(expected_scale)) {
      testthat::expect_true(parameter %in% names(formula_scale))
      testthat::expect_setequal(names(formula_scale[[parameter]]), expected_scale[[parameter]])
    }
  }

  invisible(TRUE)
}

expect_fit_sample_dimensions <- function(fit, expected_chains = NULL, expected_iterations = NULL) {
  samples <- .bayestools_fit_mcmc_list(fit)

  if (!is.null(expected_chains) && !is.na(expected_chains)) {
    testthat::expect_equal(length(samples), expected_chains)
  }
  if (!is.null(expected_iterations) && !is.na(expected_iterations)) {
    iterations <- vapply(samples, nrow, integer(1))
    testthat::expect_equal(iterations, rep(expected_iterations, length(samples)))
  }

  invisible(samples)
}
