skip_if_not_test_profile("unit")

test_that("cumulative selection initializations stay strictly positive", {

  cumulative <- prior_weightfunction(
    side = "one-sided",
    steps = .05,
    weights = wf_cumulative(c(1e-300, 1e-300))
  )

  expect_warning(
    direct_inits <- JAGS_get_inits(
      prior_list = list(bias = cumulative),
      chains = 1,
      seed = 1
    ),
    "deterministic, order-one rescaling"
  )
  for(chain_inits in direct_inits){
    expect_true(is.finite(chain_inits$omega_ratio))
    expect_true(chain_inits$omega_ratio > 0)
    expect_true(chain_inits$omega_ratio < 1)
  }

  mixture <- prior_mixture(list(
    prior_none(),
    cumulative
  ))
  expect_warning(
    mixture_inits <- JAGS_get_inits(
      prior_list = list(bias = mixture),
      chains = 1,
      seed = 1
    ),
    "deterministic, order-one rescaling"
  )
  for(chain_inits in mixture_inits){
    expect_true(is.finite(chain_inits$omega_ratio_component_2))
    expect_true(chain_inits$omega_ratio_component_2 > 0)
    expect_true(chain_inits$omega_ratio_component_2 < 1)
  }

  expect_warning(
    component_inits <- BayesTools:::.JAGS_init.weightfunction(
      cumulative,
      component_id = 2
    ),
    "deterministic, order-one rescaling"
  )
  expect_true(is.finite(component_inits$omega_ratio_component_2))
  expect_true(component_inits$omega_ratio_component_2 > 0)
  expect_true(component_inits$omega_ratio_component_2 < 1)
})

test_that("independent weight functions emit JAGS inits for free bins", {

  omega <- prior_weightfunction(
    side = "one-sided",
    steps = c(.025, .05),
    weights = wf_independent(prior("gamma", list(2, 1)))
  )
  log_omega <- prior_weightfunction(
    side = "one-sided",
    steps = .05,
    weights = wf_independent(prior("normal", list(0, 1)), scale = "log_omega")
  )

  set.seed(1)
  omega_inits <- JAGS_get_inits(list(bias = omega), chains = 1, seed = 1)[[1]]
  expect_equal(length(omega_inits$omega), 3L)
  expect_true(is.na(omega_inits$omega[[1L]]))
  expect_true(all(is.finite(omega_inits$omega[-1L])))
  expect_true(all(omega_inits$omega[-1L] > 0))

  log_inits <- JAGS_get_inits(list(bias = log_omega), chains = 1, seed = 1)[[1]]
  expect_equal(length(log_inits$log_omega), 2L)
  expect_true(is.na(log_inits$log_omega[[1L]]))
  expect_true(is.finite(log_inits$log_omega[[2L]]))

  # In a mixture the component is initialized on its local node:
  # `omega_component_2` is deterministic and expanded onto the global cuts.
  mixture <- prior_mixture(list(prior_none(), omega))
  mixture_inits <- JAGS_get_inits(list(bias = mixture), chains = 1, seed = 1)[[1]]
  expect_null(mixture_inits$omega_component_2)
  expect_equal(length(mixture_inits$omega_local_component_2), 3L)
  expect_true(is.na(mixture_inits$omega_local_component_2[[1L]]))
  expect_true(all(is.finite(mixture_inits$omega_local_component_2[-1L])))
})

test_that("Gamma initialization fallback preserves representable median proportions", {

  set.seed(1)
  expect_warning(
    initialization <- BayesTools:::.JAGS_positive_gamma_initialization(
      rep(.001, 4),
      "test latent Gamma variables"
    ),
    "deterministic, order-one rescaling"
  )
  expect_identical(initialization, rep(1, 4))

  set.seed(1)
  expect_warning(
    expect_error(
      BayesTools:::.JAGS_positive_gamma_initialization(
        c(1e-323, 2e-323),
        "test latent Gamma variables"
      ),
      "medians are not representable"
    ),
    "deterministic, order-one rescaling"
  )
})


# Initial values and model syntax are generated by separate code paths, and a
# name that drifts between them is not a soft failure: JAGS aborts with
# "Dimension mismatch in values supplied for <node>" whenever the node it does
# find has a different length. These helpers assert the general invariant --
# every initialized node is stochastic in the syntax, and lengths agree --
# rather than any particular set of names.
.selection_init_stochastic_nodes <- function(syntax){

  lines <- trimws(unlist(strsplit(paste(syntax, collapse = "\n"), "\n")))
  lines <- lines[grepl("~", lines, fixed = TRUE)]
  targets <- trimws(sub("~.*$", "", lines))
  targets <- targets[nzchar(targets)]

  indexed <- grepl("[", targets, fixed = TRUE)
  out <- list()
  for(target in targets[!indexed]){
    out[[target]] <- max(c(out[[target]], 1L))
  }
  for(target in targets[indexed]){
    parts <- strsplit(target, "[", fixed = TRUE)[[1]]
    name  <- parts[[1]]
    index <- suppressWarnings(as.integer(
      strsplit(parts[[2]], "]", fixed = TRUE)[[1]][[1]]
    ))
    if(!is.na(index)){
      out[[name]] <- max(c(out[[name]], index))
    }
  }

  out
}

expect_selection_inits_match_syntax <- function(prior_list){

  syntax <- JAGS_add_priors("model{\n}", prior_list)
  inits  <- JAGS_get_inits(prior_list = prior_list, chains = 1, seed = 1)[[1]]
  nodes  <- .selection_init_stochastic_nodes(syntax)

  for(name in setdiff(names(inits), c(".RNG.seed", ".RNG.name"))){
    expect_true(
      name %in% names(nodes),
      info = paste0("initialized node '", name, "' is not stochastic in the model syntax")
    )
    if(name %in% names(nodes)){
      expect_gte(nodes[[name]], length(inits[[name]]))
    }
  }

  invisible(inits)
}


test_that("selection initial values name stochastic nodes of the matching length", {

  independent_omega <- prior_weightfunction(
    "one-sided", c(.05, .10), wf_independent(prior("gamma", list(shape = 9, rate = 3)))
  )
  independent_log <- prior_weightfunction(
    "one-sided", c(.025),
    wf_independent(prior("normal", list(mean = log(1.5), sd = .15)), "log_omega")
  )

  # standalone priors: no cut expansion
  expect_selection_inits_match_syntax(list(bias = independent_omega))
  expect_selection_inits_match_syntax(list(bias = independent_log))

  # mixtures expand every component onto the union of all cut points, so the
  # public `omega_component_*` arrays are longer than the local ones
  mixture <- prior_mixture(list(
    prior_none(prior_weights = 1),
    prior_weightfunction("one-sided", c(.025, .05), wf_cumulative(c(1, 2, 3)), prior_weights = 1),
    independent_omega,
    independent_log,
    prior_weightfunction("two-sided", c(.05), wf_fixed(c(1, .4)), prior_weights = 1)
  ))
  inits <- expect_selection_inits_match_syntax(list(bias = mixture))

  # the initialized omega node is the local one, never the expanded target
  expect_true("omega_local_component_3" %in% names(inits))
  expect_false("omega_component_3" %in% names(inits))
  expect_true("log_omega_component_4" %in% names(inits))
})


test_that("heterogeneous weightfunction mixtures compile and adapt in JAGS", {

  # The end-to-end guard: a wrong init node name is only fatal once JAGS sees
  # the model, and only when the expansion changes the array length.
  mixture <- prior_mixture(list(
    prior_none(prior_weights = 1),
    prior_weightfunction("one-sided", c(.025, .05), wf_cumulative(c(1, 2, 3)), prior_weights = 1),
    prior_weightfunction("one-sided", c(.05, .10), wf_independent(prior("gamma", list(shape = 9, rate = 3))), prior_weights = 1),
    prior_weightfunction("one-sided", c(.025), wf_independent(prior("normal", list(mean = log(1.5), sd = .15)), "log_omega"), prior_weights = 1),
    prior_weightfunction("two-sided", c(.05), wf_fixed(c(1, .4)), prior_weights = 1)
  ))

  fit <- suppressWarnings(JAGS_fit(
    "model{}",
    data       = NULL,
    prior_list = list(bias = mixture),
    chains     = 1,
    adapt      = 50,
    burnin     = 50,
    sample     = 100,
    seed       = 14
  ))

  expect_s3_class(fit, "runjags")
  expect_false(inherits(fit, "condition"))
})
