#' @title Plot samples from the marginal posterior distributions
#'
#' @param samples samples from a posterior distribution for a
#' parameter generated by [marginal_inference].
#' @param parameter parameter name to be plotted.
#' @param ... additional arguments
#' @inheritParams plot_posterior
#' @inheritParams density.prior
#' @inheritParams plot.prior
#'
#' @return \code{plot_marginal} returns either \code{NULL} or
#' an object of class 'ggplot' if plot_type is \code{plot_type = "ggplot"}.
#'
#' @details Marginal posterior vectors may carry \code{posterior_density}
#' metadata ([posterior_metadata()]) with \code{x} and \code{y} coordinates. These densities are used
#' only when \code{density_method = "precomputed"}, which requires a matching
#' valid curve for each selected continuous leaf. Pure-atom leaves need no
#' continuous curve. Marginal plots with \code{density_method = "KDE"} use
#' a standard KDE because marginal prior-density grids are numerical density
#' ranges rather than true support metadata; this can intentionally differ from
#' the support-reflected ordinate used by \code{\link{Savage_Dickey_BF}} when
#' exact posterior-support metadata is available. A stored density describes
#' the continuous part of the posterior; point masses are drawn from the
#' declared posterior atoms (the \code{atoms} metadata, see
#' [posterior_atom_attribute()]) with either density method. A prior curve without an exact route whose numerical grid cannot
#' resolve a heavy-tailed product term is omitted with a warning of class
#' \code{BayesTools_prior_curve_unavailable}, as in [plot_posterior()], and so
#' is the prior curve of draws that declare no prior (a \code{prior_list} of
#' [prior_none()]) and carry no prior density. Other draws without a prior
#' density (e.g. from [marginal_posterior()] without prior samples) stop.
#' Direct ordered factor marginal plots omit persisted zero-design reference
#' rows and retain true non-reference point levels. They use the retained
#' level color/label list and matching dashed prior-overlay defaults of
#' [plot_posterior()]. Every non-reference continuous prior retains its finite
#' plotting ordinates, including priors with an exact infinite density point.
#' Unresolved raw numerical evaluations warn once per continuous route with
#' the classes above, distinguishing partial from whole curve unavailability
#' and retaining available points and atoms. The warning's
#' \code{unresolved_values} field contains evaluation coordinates on the source
#' scale, before any plotting transformation. Use \code{prior = FALSE} to draw
#' the posterior alone. Exact infinite density and zero-density points remain
#' valid, and finite displayed peak heights depend on the evaluation grid.
#'
#' @seealso [prior()] [marginal_inference()]  [plot_posterior()]
#' @export
plot_marginal <- function(samples, parameter, plot_type = "base", prior = FALSE,
                          n_points = 1000,
                          transformation = NULL, transformation_arguments = NULL, transformation_settings = FALSE,
                          rescale_x = FALSE, par_name = NULL, dots_prior = list(),
                          legend = TRUE, legend_title = NULL, legend_labels = NULL, legend_position = NULL,
                          ..., density_method = c("KDE", "precomputed")){

  # check input
  if(any(!sapply(samples, inherits, what = "marginal_posterior")))
    stop("'samples' must be a be an object generated by 'marginal_posterior' function.")
  check_char(parameter, "parameter")
  check_char(plot_type, "plot_type", allow_values = c("base", "ggplot"))
  check_bool(legend, "legend", allow_NA = FALSE)
  density_method <- .posterior_density_method(density_method)
  .check_transformation_input(transformation, transformation_arguments, transformation_settings)


  # get the plotting range
  dots <- list(...)
  xlim <- dots[["xlim"]]


  plot_data <- .plot_data_marginal_samples(samples, parameter = parameter, prior = prior, n_points = n_points,
                                           transformation = transformation, transformation_arguments = transformation_arguments, transformation_settings = transformation_settings,
                                           x_range = xlim,
                                           density_method = density_method)



  # add priors, if requested and available (draws without a prior density
  # that declare no prior have none, with a warning)
  plot_data_prior <- if(prior){
    unlist(lapply(plot_data, attr, which = "prior", exact = TRUE), recursive = FALSE)
  }
  if(prior && length(plot_data_prior) > 0L){

    # Resolve one plotting range for the jointly displayed prior and posterior.
    plot_data_joined <- c(plot_data, plot_data_prior)
    dots_prior <- .transfer_dots(dots_prior, ...)
    dots_prior <- .plot_ordered_overlay_styles(dots_prior, plot_data, list(...))

    if(is.null(dots_prior[["xlim"]])){
      dots_prior$xlim <- range(as.vector(sapply(plot_data_joined, attr, which = "x_range")))
    }

    is_simple <- sapply(plot_data_joined, inherits, what = "density.prior.simple")
    is_point  <- sapply(plot_data_joined, inherits, what = "density.prior.point")
    if(any(is_simple) && any(is_point)){
      if(is.null(dots_prior[["ylim"]])){
        dots_prior$ylim <- range(as.vector(sapply(plot_data_joined[is_simple], attr, which = "y_range", exact = TRUE)))
      }
      if(is.null(dots_prior[["ylim2"]])){
        dots_prior$ylim2 <- range(as.vector(sapply(plot_data_joined[is_point], attr, which = "y_range", exact = TRUE)))
      }
    }else{
      if(is.null(dots_prior[["ylim"]])){
        dots_prior$ylim <- range(as.vector(sapply(plot_data_joined, attr, which = "y_range", exact = TRUE)))
      }
    }
    if(!is.null(dots[["scale_y2"]])){
      dots_prior$scale_y2 <- dots[["scale_y2"]]
    }
    scale_y2 <- .plot_scale_y2_resolve(plot_data_joined, dots_prior)


    # plot prior
    args_prior           <- dots_prior
    args_prior$plot_data <- plot_data_prior
    args_prior$plot_type <- plot_type
    args_prior$par_name  <- par_name
    args_prior$scale_y2  <- scale_y2
    args_prior$hardcode  <- TRUE
    args_prior$legend    <- FALSE
    args_prior$legend_title <- legend_title
    args_prior$legend_labels <- legend_labels
    args_prior$legend_position <- legend_position

    plot <- do.call(.plot_prior_list.factor, args_prior)


    # plot posterior
    args           <- list(...)
    args$plot_data <- plot_data
    args$plot_type <- plot_type
    args$par_name  <- par_name
    args$add       <- TRUE
    args$legend    <- legend
    args$legend_title <- legend_title
    args$legend_labels <- legend_labels
    args$legend_position <- legend_position

    if(plot_type == "base"){
      plot <- do.call(.plot_prior_list.factor, args)
    }else if(plot_type == "ggplot"){
      args$scale_y2 <- scale_y2
      plot <- plot + do.call(.plot_prior_list.factor, args)
    }

  }else{

    # plot just posterior otherwise
    plot <- .plot_prior_list.factor(
      plot_data = plot_data, plot_type = plot_type, par_name = par_name,
      legend = legend, legend_title = legend_title, legend_labels = legend_labels,
      legend_position = legend_position, ...
    )

  }


  if(plot_type == "ggplot"){
    return(plot)
  }else{
    return(invisible())
  }

}

.plot_data_marginal_samples     <- function(samples, parameter, prior, n_points, transformation, transformation_arguments, transformation_settings,
                                            x_range = NULL,
                                            density_method = c("KDE", "precomputed")){

  check_list(samples, "samples", check_names = parameter, allow_other = TRUE)
  density_method <- .posterior_density_method(density_method)

  # extract the relevant information
  posterior_samples   <- .plot_data_marginal_level_samples(samples, parameter)
  prior_densities     <- .marginal_posterior_parameter_prior_densities(samples, parameter)
  posterior_densities <- .marginal_posterior_parameter_posterior_densities(samples, parameter)
  level_metadata <- samples[[parameter]]
  levels <- if(is.list(level_metadata)) level_metadata else list(level_metadata)
  if(identical(density_method, "precomputed")){
    posterior_densities <- lapply(seq_along(levels), function(i){
      name <- if(is.null(names(levels))) parameter else names(levels)[[i]]
      .plot_data_selected_posterior_density(level_metadata, levels[[i]], name)
    })
  }
  reference <- attr(level_metadata, "factor_reference_levels", exact = TRUE)
  if(isTRUE(attr(level_metadata, "ordered", exact = TRUE)) && !is.null(reference)){
    if(!identical(names(reference), names(posterior_samples))){
      stop("The persisted reference-level metadata do not match the marginal factor levels.", call. = FALSE)
    }
    posterior_samples <- posterior_samples[!reference]
    prior_densities <- prior_densities[!reference]
    posterior_densities <- posterior_densities[!reference]
    levels <- levels[!reference]
  }
  if(prior){
    for(level in levels) .bt_formula_measure_check(level, "prior_density")
    missing <- vapply(prior_densities, is.null, logical(1))
    # levels that declare no prior (prior_none()) have no prior curve; any
    # other level without a prior density was created without one
    without_prior <- vapply(levels, .plot_data_samples_without_prior, logical(1))
    if(any(missing & !without_prior))
      stop("'samples' did not contain prior densities")
  }


  # create the output object
  out <- list()


  # deal with the densities
  for(i in seq_along(posterior_samples)){

    out_level <- .plot_data_marginal_samples.den(
      posterior_samples[[i]],
      n_points,
      transformation,
      transformation_arguments,
      transformation_settings,
      posterior_density = posterior_densities[[i]],
      density_method    = density_method
    )

    for(j in seq_along(out_level)){
      attr(out_level[[j]], "level")      <- i
      attr(out_level[[j]], "level_name") <- names(posterior_samples)[i]
    }

    if(prior && !is.null(prior_densities[[i]])){
      out_den.prior <- .prior_linear_density_to_plot_data(
        prior_densities[[i]],
        n_points                  = n_points,
        x_range                   = x_range,
        transformation            = transformation,
        transformation_arguments  = transformation_arguments,
        transformation_settings   = transformation_settings,
        factor                    = TRUE,
        level                     = i,
        level_name                = names(posterior_samples)[i]
      )

      attr(out_level[[1]], "prior") <- out_den.prior
    }

    for(j in seq_along(out_level)){
      out[[paste0(names(out_level)[j], i)]] <- out_level[[j]]
    }

  }

  # warn only once the posterior layers exist (draws without an atom
  # declaration stop above, without a plot)
  if(prior && any(vapply(prior_densities, is.null, logical(1)))){
    .plot_data_warn_prior_curve_unavailable(parameter)
  }

  ordered <- isTRUE(attr(level_metadata, "ordered", exact = TRUE)) || any(vapply(levels, function(x){
    !is.null(.bt_meta_get(x, "ordered_source"))
  }, logical(1)))
  for(i in seq_along(out)){
    prior_data <- attr(out[[i]], "prior", exact = TRUE)
    if(!is.null(prior_data)){
      attr(out[[i]], "prior") <- .plot_factor_level_universe(prior_data,
        names(posterior_samples), ordered = ordered)
    }
  }
  .plot_factor_level_universe(out, names(posterior_samples), ordered = ordered)
}
# Numeric draws of each marginal posterior level with their declared atoms.
.plot_data_marginal_level_samples <- function(samples, parameter){

  levels <- samples[[parameter]]
  if(!is.list(levels)){
    levels <- stats::setNames(list(levels), parameter)
  }

  lapply(levels, function(level){
    atoms <- .posterior_atoms_get(level, allow_partial = TRUE)
    if(is.null(atoms)) .bt_formula_measure_check(level, "atoms")
    if(!is.null(atoms) && !atoms$joint_declared){
      if(ncol(atoms$locations) != 1L){
        .bt_formula_measure_check(level, "atoms")
        stop(atoms$joint_unavailable)
      }
      scalar <- .posterior_atoms_for_column(atoms, 1L)
      if(is.null(scalar)){
        .bt_formula_measure_check(level, "atoms")
        stop(atoms$joint_unavailable)
      }
      atoms <- scalar
    }
    out <- as.numeric(level)
    if(!is.null(atoms)){
      out <- .posterior_atoms_set(out, atoms)
    }
    out
  })
}
.plot_data_marginal_samples.den <- function(x, n_points, transformation, transformation_arguments, transformation_settings,
                                            posterior_density = NULL,
                                            density_method = c("KDE", "precomputed")){

  .bt_ordered_source_require_measure(x)
  x_points        <- NULL
  y_points        <- NULL
  density_method <- .posterior_density_method(density_method)
  posterior_density <- .posterior_density_for_method(posterior_density, density_method)
  posterior_atoms <- .posterior_atoms_get(x, allow_partial = TRUE)

  if(is.null(posterior_atoms)){
    .bt_formula_measure_check(x, "atoms")
    .plot_data_stop_unknown_atoms()
  }
  if(ncol(posterior_atoms$locations) != 1L){
    stop("Marginal posterior plotting is unavailable for multivariate atom metadata.", call. = FALSE)
  }
  posterior_atoms <- .posterior_atoms_for_column(posterior_atoms, 1L)
  if(is.null(posterior_atoms)){
    .bt_formula_measure_check(x, "atoms")
    .plot_data_stop_unknown_atoms()
  }
  continuous <- .Savage_Dickey_BF.continuous_posterior(x, posterior_atoms)
  samples_density <- as.numeric(continuous$samples)
  continuous_mass <- continuous$continuous_mass
  .plot_data_require_precomputed_density(posterior_density, density_method, continuous_mass)
  if(nrow(posterior_atoms$locations) > 0L){
    x_points <- as.numeric(posterior_atoms$locations[, 1L])
    y_points <- posterior_atoms$mass
  }

  # create the output object
  out <- list()

  # get the density estimate (a stored density is the continuous part; the
  # point masses are the declared posterior atoms)
  if(!is.null(posterior_density)){
    x_den <- posterior_density[["x"]]
    y_den <- posterior_density[["y"]]

    if(!is.null(transformation)){
      transformed <- .density.prior_transformation_grid(x_den, y_den, transformation, transformation_arguments)
      x_den <- transformed$x[!transformed$drop]
      y_den <- transformed$y[!transformed$drop]
      samples_density <- .density.prior_transformation_x(samples_density, transformation, transformation_arguments)
    }

    out_den <- list(
      call    = call("density", "stored posterior density"),
      bw      = NULL,
      n       = length(x_den),
      x       = x_den,
      y       = y_den,
      samples = samples_density
    )

    class(out_den) <- c("density", "density.prior", "density.prior.factor", "density.prior.simple")
    attr(out_den, "x_range")    <- range(x_den)
    attr(out_den, "y_range")    <- c(0, max(y_den))
    attr(out_den, "posterior_density_method") <- posterior_density[["method"]]
    attr(out_den, "posterior_density_diagnostics") <- posterior_density[["diagnostics"]]

    out[["density"]] <- out_den

  }else if(continuous_mass > 0 && length(samples_density) > 1 && diff(range(samples_density)) > 0){
    args <- list(x = samples_density, n = n_points)

    density_continuous <- do.call(stats::density, args)
    x_den    <- density_continuous$x
    y_den    <- density_continuous$y * continuous_mass

    # apply transformations
    if(!is.null(transformation)){
      x_den           <- .density.prior_transformation_x(x_den, transformation, transformation_arguments)
      y_den           <- .density.prior_transformation_y(x_den, y_den, transformation, transformation_arguments)
      samples_density <- .density.prior_transformation_x(samples_density, transformation, transformation_arguments)
    }

    out_den <- list(
      call    = call("density", "mixed samples"),
      bw      = NULL,
      n       = n_points,
      x       = x_den,
      y       = y_den,
      samples = samples_density
    )

    class(out_den) <- c("density", "density.prior", "density.prior.factor", "density.prior.simple")
    attr(out_den, "x_range")    <- range(x_den)
    attr(out_den, "y_range")    <- c(0, max(y_den))

    out[["density"]] <- out_den

  }else if(continuous_mass > 0){
    stop(
      "Posterior density is unavailable for declared continuous samples with fewer than two distinct values. ",
      "Provide valid 'posterior_density' metadata (posterior_metadata()) and set 'density_method' to 'precomputed'.",
      call. = FALSE
    )
  }

  if(!is.null(y_points)){
    if(!is.null(transformation)){
      x_points <- .density.prior_transformation_checked_x(x_points, transformation, transformation_arguments)
    }

    for(i in seq_along(y_points)){
      temp_points <- list(
        call    = call("density", paste0("point", i)),
        bw      = NULL,
        n       = n_points,
        x       = x_points[i],
        y       = y_points[i],
        samples = NULL
      )

      class(temp_points) <- c("density", "density.prior", "density.prior.point", "density.prior.factor")
      attr(temp_points, "x_range") <- range(x_points)
      attr(temp_points, "y_range") <- c(0, max(y_points))

      out[[paste0("points", i)]] <- temp_points
    }
  }

  return(out)
}
