#' @title Plot estimates from models
#'
#' @details Plots prior and posterior estimates of the same parameter
#' across multiple models (prior distributions with orthonormal/meandif contrast
#' are always plotted as differences from the grand mean).
#' Ordered factors use the retained semantic level effects, omitting their
#' zero-design reference rows, and per-model transformed level summaries.
#' The model-averaged estimate uses the selected scalar level draws.
#' With \code{prior = FALSE}, no prior means or intervals are computed; model
#' probabilities and Bayes factors remain available for updating labels.
#' With \code{prior = TRUE}, ordered level means use the total mean and exact
#' allocation expectations with the persisted design. Their equal-tail 95\%
#' intervals use structural prior probabilities and generalized quantiles,
#' including exact jumps at point masses. No sampled prior means or quantiles
#' are substituted. An undefined mean, unresolved expression, unsupported
#' structural probability route, or unavailable numerical diagnostics raises
#' \code{BayesTools_prior_interval_unavailable} (also
#' \code{BayesTools_plot_condition}), identifying the model and level; set
#' \code{prior = FALSE} to plot posterior estimates.
#'
#' @param parameter parameter name to be plotted. Does not support
#' PET-PEESE and weightfunction.
#' @param inference object created by [ensemble_inference] function
#' @param conditional whether conditional models should be displayed
#' @param order list specifying ordering of the models. The first
#' element describes whether the ordering should be \code{"increasing"}
#' or \code{"decreasing"} and the second element describes whether
#' the ordering should be based \code{"model"} order, \code{"estimate"}
#' size, posterior \code{"probability"}, or the inclusion \code{"BF"}.
#' @param ... additional arguments. E.g.:
#' \describe{
#'   \item{\code{"show_updating"}}{whether Bayes factors and change from
#'   prior to posterior odds should be shown on the secondary y-axis}
#'   \item{\code{"show_estimates"}}{whether posterior estimates and 95% CI
#'   should be shown on the secondary y-axis}
#'   \item{\code{"y_axis2"}}{whether the secondary y-axis should be shown}
#' }
#' @inheritParams ensemble_inference
#' @inheritParams plot.prior
#' @inheritParams plot_posterior
#' @inheritParams format_parameter_names
#'
#' @return \code{plot_models} returns either \code{NULL} or
#' an object of class 'ggplot' if plot_type is \code{plot_type = "ggplot"}.
#'
#' @seealso [prior()] [lines_prior_list()]  [geom_prior_list()]
#' @export
plot_models <- function(model_list, samples, inference, parameter, plot_type = "base", prior = FALSE, conditional = FALSE,
                        order = NULL,
                        transformation = NULL, transformation_arguments = NULL, transformation_settings = FALSE,
                        par_name = NULL, formula_prefix = TRUE, ...){

  # check input
  check_list(model_list, "model_list")
  check_char(parameter, "parameter")
  sapply(model_list, function(m)check_list(m, "model_list:model", check_names = "fit_summary", all_objects = TRUE, allow_other = TRUE))
  if(!all(unlist(sapply(model_list, function(m) sapply(attr(m[["fit"]], "prior_list"), function(p) is.prior(p))))))
    stop("model_list:priors must contain 'BayesTools' priors")
  if(!all(sapply(model_list, function(m)inherits(m[["fit_summary"]], what = "BayesTools_runjags_summary"))))
    stop("model_list:fit_summary must contain 'BayesTools' fit_summary")
  check_list(samples, "samples")
  if(any(!sapply(samples, inherits, what = "mixed_posteriors")))
    stop("'samples' must be a be an object generated by 'mix_posteriors' function.")
  check_list(order, "order", allow_NULL = TRUE)
  if(!is.null(order)){
    check_list(order, "order", check_length = 2)
    check_char(order[[1]], allow_values = c("decreasing", "increasing"))
    check_char(order[[2]], allow_values = c("model", "estimate", "probability", "BF"))
  }

  # extract the objects
  models_summary   <- lapply(model_list, function(m)m[["fit_summary"]])
  models_inference <- lapply(model_list, function(m)m[["inference"]])
  total_inference  <- inference[[parameter]]
  total_samples    <- samples[[parameter]]
  prior_list       <- attr(total_samples, "prior_list")

  # deal with factors
  if(inherits(total_samples, "mixed_posteriors.factor")){

    # make sure that the orthonormal/meandif priors are transformed to differences from the mean
    ordered <- any(vapply(if(is.prior(prior_list)) list(prior_list) else prior_list,
      is.prior.ordered, logical(1)))
    if(isTRUE(attr(total_samples, "orthonormal")) ||
       isTRUE(attr(total_samples, "meandif")) || ordered){

      # transform the samples
      if(ordered || ncol(total_samples) == attr(total_samples, "levels")){
        total_samples <- transform_factor_samples(samples)[[parameter]]
      }
      if(ordered){
        total_samples <- .transformed_factor_drop_structural_levels(total_samples)
      }
      # transform the model summaries
      if(!all(vapply(models_summary, function(m) all(colnames(total_samples) %in% attr(m, "parameters")), logical(1)))){
        models_summary <- lapply(model_list, function(m) JAGS_estimates_table(m[["fit"]], transform_factors = TRUE))
      }

    }

    parameter <- colnames(total_samples)
  }

  # prepare nice parameter names
  if(is.null(par_name)){
    par_name  <- .bt_label(
      .bt_draws_label_parts(total_samples, parameter[[1L]]),
      style          = "table",
      formula_prefix = formula_prefix
    )
  }

  plot <- list()
  for(i in seq_along(parameter)){
    plot[[i]] <- .plot_models.simple(models_summary = models_summary, models_inference = models_inference, total_inference = total_inference, total_samples = total_samples,
                                     prior_list = prior_list, parameter = parameter[i], par_name = par_name[i],
                                     plot_type = plot_type, prior = prior, conditional = conditional, order = order,
                                     transformation = transformation, transformation_arguments = transformation_arguments, transformation_settings = transformation_settings, ...)
  }


  # return the plots
  if(plot_type == "base"){
    return(invisible())
  }else if(plot_type == "ggplot"){
    if(length(parameter) == 1){
      plot <- plot[[i]]
    }
    return(plot)
  }
}

.plot_models_data_prior     <- function(prior_list, models_inference, prior = TRUE,
                                        parameter = NULL){

  summaries <- if(prior) lapply(seq_along(prior_list), function(i){
    if(is.prior.ordered(prior_list[[i]])){
      .plot_models_ordered_prior_summary(prior_list[[i]], parameter, i)
    }else{
      c(mean(prior_list[[i]]), mquant(prior_list[[i]], .025), mquant(prior_list[[i]], .975))
    }
  }) else rep(list(rep(NA_real_, 3L)), length(prior_list))
  return(data.frame(
    model      = seq_along(prior_list),
    y          = vapply(summaries, `[[`, numeric(1), 1L),
    y_lCI      = vapply(summaries, `[[`, numeric(1), 2L),
    y_uCI      = vapply(summaries, `[[`, numeric(1), 3L),
    prior_prob = sapply(models_inference, function(m)m[["prior_prob"]]),
    post_prob  = sapply(models_inference, function(m)m[["post_prob"]]),
    BF         = sapply(models_inference, function(m)m[["inclusion_BF"]])
  ))
}
.plot_models_prior_unavailable <- function(model, parameter, reason){

  stop(structure(list(message = paste0(
    "Prior interval/mean for model ", model, " and level '", parameter,
    "' is unavailable: ", sub("[.]$", "", reason),
    ". Set 'prior = FALSE' to plot posterior estimates."
  ), call = NULL, model = model, level = parameter, reason = reason),
    class = c("BayesTools_prior_interval_unavailable", "BayesTools_plot_condition",
      "error", "condition")))
}
.plot_models_prior_mean <- function(prior){

  if(is.prior.mixture(prior) || is.prior.spike_and_slab(prior)){
    probabilities <- .prior_density_ordinate_mixture_weights(prior)
    if(is.null(probabilities)) stop("component probabilities are unavailable")
    components <- lapply(prior[probabilities > 0], .plot_models_prior_mean)
    return(Reduce(`+`, Map(`*`, components, probabilities[probabilities > 0])))
  }
  if(is.prior.none(prior)) return(0)
  mean(prior)
}
.plot_models_ordered_prior_summary <- function(prior, parameter, model){

  unavailable <- function(reason) .plot_models_prior_unavailable(model, parameter, reason)
  metadata <- .prior_ordered_metadata(prior)
  level_names <- .bt_label(.bt_label_factor_level_parts(metadata$parameter_name, prior,
    transformation = "none"), style = "selector")
  level <- match(parameter, level_names)
  if(is.na(level)) unavailable("the persisted level design does not identify this level")
  design <- as.matrix(.factor_term_design_from_metadata(prior)$design)
  weights <- design[level, ]
  means <- tryCatch(.plot_models_prior_mean(prior$total), error = function(e) e)
  if(inherits(means, "error")) unavailable(paste0("the total mean is unavailable (", conditionMessage(means), ")"))
  if(!is.numeric(means) || any(!is.finite(means)) ||
     !length(means) %in% c(1L, metadata$theta_dim)){
    unavailable("the total mean is undefined, non-finite, or depends on an unresolved expression")
  }
  if(length(means) == 1L) means <- rep(means, metadata$theta_dim)
  coefficient_means <- means[metadata$slice_index]
  for(i in seq_along(coefficient_means)){
    for(factor in metadata$ordered_terms){
      allocation <- .prior_ordered_allocation_for_coefficient(metadata, factor,
        metadata$slice_index[[i]])
      expectations <- if(identical(allocation$spec$type, "fixed")){
        allocation$spec$weights
      }else{
        allocation$spec$alpha / sum(allocation$spec$alpha)
      }
      increment <- metadata$coefficient_grid[[factor]][[i]]
      coefficient_means[[i]] <- coefficient_means[[i]] * expectations[[increment]]
    }
  }
  prior_mean <- sum(weights * coefficient_means)
  if(!is.finite(prior_mean)) unavailable("the level mean is non-finite")
  columns <- .JAGS_prior_factor_names(metadata$parameter_name, prior)
  weights <- stats::setNames(weights, columns)
  context <- .prior_density_context(stats::setNames(list(prior), metadata$parameter_name), columns)
  dist <- tryCatch(.prior_density_from_context(context, weights), error = function(e) e)
  if(inherits(dist, "error")) unavailable(conditionMessage(dist))
  intervals <- .plot_models_prior_quantiles(dist, c(.025, .975), model, parameter)
  c(prior_mean, intervals)
}
.plot_models_prior_quantiles <- function(dist, probabilities, model, parameter){

  unavailable <- function(reason) .plot_models_prior_unavailable(model, parameter, reason)
  route <- .prior_density_route_from_adaptive(attr(dist, "adaptive_evaluation", exact = TRUE))
  if(is.null(route) || .prior_density_route_has_leaf(route, "unknown")){
    unavailable("the structural prior probability route is unsupported")
  }
  if(identical(route$type, "scalar") && is.null(route$source_transform) &&
     is.prior.simple(route$prior) && !is.prior.discrete(route$prior)){
    p <- if(route$scale < 0) 1 - probabilities else probabilities
    return(route$offset + route$scale * quant(route$prior, p))
  }
  if(identical(route$type, "normal")){
    normal <- .prior_density_ordinate_linear_normal(route$prior_list,
      route$weights, route$source_transforms, 0)
    return(stats::qnorm(probabilities, normal$provenance$mean, normal$provenance$sd))
  }
  cdf_at <- function(value){
    region <- list(intervals = .prior_region_intervals(-Inf, value),
      indicator = function(x) x <= value)
    probability <- tryCatch(.prior_linear_density_region_probability(dist, region),
      error = function(e) e)
    if(inherits(probability, "error")) unavailable(conditionMessage(probability))
    diagnostics <- attr(probability, "numerical_diagnostics", exact = TRUE)
    if(is.null(probability) || length(probability) != 1L ||
       !is.finite(probability) || probability < 0 || probability > 1 ||
       is.null(diagnostics) || !is.finite(diagnostics$absolute_error)){
      unavailable("the structural prior probability or its error diagnostics are unavailable")
    }
    as.numeric(probability)
  }
  atoms <- dist$points
  if(is.null(atoms)) atoms <- data.frame(x = numeric(), p = numeric())
  atoms <- atoms[atoms$p > 0, , drop = FALSE]
  atoms <- atoms[order(atoms$x), , drop = FALSE]
  if(identical(route$type, "atom")){
    return(vapply(probabilities, function(p) atoms$x[which(cumsum(atoms$p) >= p)[1L]], numeric(1)))
  }
  source_hull <- function(route){
    switch(route$type,
      "atom" = range(route$locations),
      "scalar" = if(is.null(route$source_transform)){
        bounds <- .prior_linear_group_support_hull(list(prior = route$prior,
          weights = c(source = 1), indices = 1L))
        if(is.null(bounds)) NULL else route$offset + sort(route$scale * bounds)
      }else NULL,
      "normal" = c(-Inf, Inf),
      "conditional_normal" = c(-Inf, Inf),
      "scale_product" = .prior_scale_product_hull(route$spec),
      "mixture" = {
        hulls <- lapply(route$components[route$weights > 0], source_hull)
        if(any(vapply(hulls, is.null, logical(1)))) NULL else range(unlist(hulls))
      },
      NULL)
  }
  hull <- source_hull(route)
  if(is.null(hull)){
    hull <- .prior_linear_density_support_hull(attr(dist, "adaptive_evaluation", exact = TRUE))
  }
  if(is.null(hull)) hull <- c(-Inf, Inf)
  limits <- .prior_linear_density_range(dist)
  vapply(probabilities, function(p){
    atom_cdf <- if(nrow(atoms) > 0L) vapply(atoms$x, cdf_at, numeric(1)) else numeric()
    jump <- which(p > atom_cdf - atoms$p & p <= atom_cdf)
    if(length(jump) > 0L) return(atoms$x[jump[[1L]]])
    lower <- if(is.finite(hull[1L])) hull[1L] else limits[1L]
    upper <- if(is.finite(hull[2L])) hull[2L] else limits[2L]
    if(!all(is.finite(c(lower, upper)))) unavailable("finite starting bounds are unavailable")
    span <- max(1, upper - lower)
    lower_cdf <- cdf_at(lower)
    upper_cdf <- cdf_at(upper)
    if((lower_cdf > p && is.finite(hull[1L])) ||
       (upper_cdf < p && is.finite(hull[2L]))){
      unavailable("the source support bounds do not bracket the requested probability")
    }
    for(i in seq_len(1024L)){
      if(lower_cdf <= p && upper_cdf >= p) break
      if(lower_cdf > p && !is.finite(hull[1L])) lower <- lower - span
      if(upper_cdf < p && !is.finite(hull[2L])) upper <- upper + span
      if(!all(is.finite(c(lower, upper)))) unavailable("the checked prior probability bracket overflowed")
      lower_cdf <- cdf_at(lower)
      upper_cdf <- cdf_at(upper)
      span <- span * 2
    }
    if(lower_cdf > p || upper_cdf < p) unavailable("the source support bounds do not bracket the requested probability")
    if(length(atom_cdf) > 0L){
      before <- which(atom_cdf < p)
      after <- which(atom_cdf - atoms$p >= p)
      if(length(before) > 0L) lower <- max(lower, atoms$x[before])
      if(length(after) > 0L) upper <- min(upper, atoms$x[after])
    }
    if(lower == upper) return(lower)
    upper_atom <- match(upper, atoms$x)
    objective <- function(x){
      value <- cdf_at(x)
      if(x == upper && !is.na(upper_atom)) value <- value - atoms$p[[upper_atom]]
      value - p
    }
    result <- tryCatch(stats::uniroot(objective, c(lower, upper),
      tol = sqrt(.Machine$double.eps)), error = function(e) e)
    if(inherits(result, "error")) unavailable(conditionMessage(result))
    result$root
  }, numeric(1))
}
.plot_models_data_posterior <- function(models_summary, parameter, prior_list, models_inference){
  return(data.frame(
    model      = 1:length(models_summary),
    y          = sapply(1:length(models_summary), function(i){
      if(any(attr(models_summary[[i]], "parameters") == parameter)){
        return(models_summary[[i]][attr(models_summary[[i]], "parameters") == parameter, "Mean"])
      }else if(is.prior.point(prior_list[[i]])){
        return(prior_list[[i]]$parameters[["location"]])
      }else{
        stop(paste0("Posterior distribution summary for '", parameter, "' is not available."))
      }
    }),
    y_lCI      = sapply(1:length(models_summary), function(i){
      if(any(attr(models_summary[[i]], "parameters") == parameter)){
        return(models_summary[[i]][attr(models_summary[[i]], "parameters") == parameter, "0.025"])
      }else if(is.prior.point(prior_list[[i]])){
        return(prior_list[[i]]$parameters[["location"]])
      }else{
        stop(paste0("Posterior distribution for '", parameter, "' is not available."))
      }
    }),
    y_uCI      = sapply(1:length(models_summary), function(i){
      if(any(attr(models_summary[[i]], "parameters") == parameter)){
        return(models_summary[[i]][attr(models_summary[[i]], "parameters") == parameter, "0.975"])
      }else if(is.prior.point(prior_list[[i]])){
        return(prior_list[[i]]$parameters[["location"]])
      }else{
        stop(paste0("Posterior distribution for '", parameter, "' is not available."))
      }
    }),
    prior_prob = sapply(models_inference, function(m) m[["prior_prob"]]),
    post_prob  = sapply(models_inference, function(m) m[["post_prob"]]),
    BF         = sapply(models_inference, function(m) m[["inclusion_BF"]])
  ))
}
.plot_models.simple         <- function(models_summary, models_inference, total_inference, total_samples,
                                        prior_list, parameter, par_name,
                                        plot_type, prior, conditional, order,
                                        transformation, transformation_arguments, transformation_settings, ...){

  # create a table with results
  prior_data     <- .plot_models_data_prior(prior_list, models_inference,
    prior = prior, parameter = parameter)
  posterior_data <- .plot_models_data_posterior(models_summary, parameter, prior_list, models_inference)

  # remove null models if requested (assuming that the overall estimate is already supplied accordingly)
  if(conditional){
    prior_data     <- prior_data[!attr(total_inference, "is_null"),]
    posterior_data <- posterior_data[!attr(total_inference, "is_null"),]
  }

  # apply ordering
  if(!is.null(order)){
    prior_data <- switch(
      order[[2]],
      "model"       = prior_data[order(posterior_data$model,      decreasing = order[[1]] == "decreasing"),],
      "estimate"    = prior_data[order(posterior_data$y,          decreasing = order[[1]] == "decreasing"),],
      "probability" = prior_data[order(posterior_data$post_prob,  decreasing = order[[1]] == "decreasing"),],
      "BF"          = prior_data[order(posterior_data$BF,         decreasing = order[[1]] == "decreasing"),]
    )
    posterior_data <- switch(
      order[[2]],
      "model"       = posterior_data[order(posterior_data$model,      decreasing = order[[1]] == "decreasing"),],
      "estimate"    = posterior_data[order(posterior_data$y,          decreasing = order[[1]] == "decreasing"),],
      "probability" = posterior_data[order(posterior_data$post_prob,  decreasing = order[[1]] == "decreasing"),],
      "BF"          = posterior_data[order(posterior_data$BF,         decreasing = order[[1]] == "decreasing"),]
    )
  }

  # compute overall estimate for the requested parameter only
  samples_for_overall <- total_samples
  if((is.matrix(total_samples) || is.data.frame(total_samples)) &&
     NCOL(total_samples) > 1L){
    if(is.null(colnames(total_samples)) || !parameter %in% colnames(total_samples)){
      stop(
        "Overall plot_models estimate requires a column named '", parameter, "'.",
        call. = FALSE
      )
    }
    samples_for_overall <- total_samples[, parameter]
  }
  overal_mean <- mean(samples_for_overall)
  overal_lCI  <- unname(stats::quantile(samples_for_overall, .025))
  overal_uCI  <- unname(stats::quantile(samples_for_overall, .975))
  vertical_0  <- 0

  # apply transformations
  if(!is.null(transformation)){
    prior_data[,c("y", "y_lCI","y_uCI")]     <- .density.prior_transformation_x(prior_data[,c("y", "y_lCI","y_uCI")],   transformation, transformation_arguments)
    posterior_data[,c("y", "y_lCI","y_uCI")] <- .density.prior_transformation_x(posterior_data[,c("y", "y_lCI","y_uCI")],   transformation, transformation_arguments)
    overal_mean <- .density.prior_transformation_x(overal_mean, transformation, transformation_arguments)
    overal_lCI  <- .density.prior_transformation_x(overal_lCI,  transformation, transformation_arguments)
    overal_uCI  <- .density.prior_transformation_x(overal_uCI , transformation, transformation_arguments)
    vertical_0  <- .density.prior_transformation_x(vertical_0 , transformation, transformation_arguments)
  }

  # add names and locations
  prior_data$x     <- 3:(nrow(prior_data) + 2)     + .25
  posterior_data$x <- 3:(nrow(posterior_data) + 2)

  posterior_data$y_labels2  <- paste0(
    format(round(posterior_data$y, 2), nsmall = 2),
    " [", format(round(posterior_data$y_lCI, 2), nsmall = 2), ", ",
    format(round(posterior_data$y_uCI, 2), nsmall = 2), "]")
  prior_data$y_labels2      <- paste0(
    "BF = ", format(round(prior_data$BF, 2), nsmall = 2),
    " [", format(round(prior_data$prior_prob, 2), nsmall = 2), " -> ", format(round(prior_data$post_prob, 2), nsmall = 2),"]")
  overal_y_label  <- "Model-Averaged"
  overal_y_label2 <- paste0(
    format(round(overal_mean, 2), nsmall = 2), " [", format(round(overal_lCI, 2), nsmall = 2), ", ",
    format(round(overal_uCI, 2), nsmall = 2), "]")


  # set the plotting values
  dots      <- list(...)

  show_updating  <- is.null(dots[["show_updating"]])  || dots[["show_updating"]]
  show_estimates <- is.null(dots[["show_estimates"]]) || dots[["show_estimates"]]

  y_at      <- c(1,               posterior_data$x)
  y_labels  <- c(overal_y_label,  paste0("Model ", posterior_data$model))
  y_at2     <- c(1,               posterior_data$x[show_estimates],         prior_data$x[show_updating])
  y_labels2 <- c(overal_y_label2, posterior_data$y_labels2[show_estimates], prior_data$y_labels2[show_updating])
  ylim      <- c(0, max(posterior_data$x) + 1)


  if(!is.null(dots[["xlim"]])){
    xlim     <- dots[["xlim"]]
    x_labels <- pretty(xlim)
  }else{
    x_labels  <- pretty(range(c(posterior_data$y_lCI, posterior_data$y_uCI, overal_lCI, overal_uCI, if(prior) c(prior_data$y_lCI, prior_data$y_uCI))))
    xlim      <- range(x_labels)
  }
  if(!is.null(dots[["xlab"]])){
    xlab <- dots[["xlab"]]
  }else{
    xlab <- if(is.null(par_name)) parameter else bquote(.(par_name))
  }
  if(!is.null(dots[["cex"]])){
    cex  <- dots[["cex"]]
  }else{
    cex  <- 4
  }
  if(!is.null(dots[["col2"]])){
    col2  <- dots[["col2"]]
  }else{
    col2  <- "grey80"
  }
  if(!is.null(dots[["col"]])){
    col   <- dots[["col"]]
  }else{
    col   <- "black"
  }


  ### do the plotting
  if(plot_type == "base"){

    oldpar <- graphics::par(no.readonly = TRUE)
    on.exit(graphics::par(mar = oldpar[["mar"]]))

    # set up margins
    if(length(dots[["mar"]]) == 0){
      graphics::par(mar = c(4, max(nchar(y_labels)) * 2/3, 0, max(nchar(y_labels2)) * 1/2))
    }else{
      graphics::par(mar = dots[["mar"]])
    }

    graphics::plot(NA, bty = "n", las = 1, xlab = xlab, ylab = "", main = "", yaxt = "n", ylim = ylim, xlim = xlim)
    graphics::axis(2, at = y_at,  labels = y_labels,  las = 1, col = NA)
    if(is.null(dots[["y_axis2"]]) || (!is.null(dots[["y_axis2"]]) && dots[["y_axis2"]])){
      graphics::axis(4, at = y_at2, labels = y_labels2, las = 1, col = NA, hadj = 0)
    }
    graphics::abline(v = vertical_0, lty = 3)

    graphics::arrows(
      x0 = posterior_data$y_lCI[posterior_data$y_uCI - posterior_data$y_lCI > 0],
      x1 = posterior_data$y_uCI[posterior_data$y_uCI - posterior_data$y_lCI > 0],
      y0 = posterior_data$x[posterior_data$y_uCI - posterior_data$y_lCI > 0],
      code = 3, angle = 90, length = 0.1, col = col)
    graphics::points(posterior_data$y, posterior_data$x, pch = 15, cex = cex*prior_data$post_prob, col = col)

    if(prior){
      graphics::arrows(
        x0 = prior_data$y_lCI[prior_data$y_uCI - prior_data$y_lCI > 0],
        x1 = prior_data$y_uCI[prior_data$y_uCI - prior_data$y_lCI > 0],
        y0 = prior_data$x[prior_data$y_uCI - prior_data$y_lCI > 0],
        code = 3, angle = 90, length = 0.1, col = col2)
      graphics::points(prior_data$y, prior_data$x, pch = 15, cex = cex*prior_data$prior_prob, col = col2)
    }


    graphics::polygon(
      x = c(overal_lCI, overal_mean , overal_uCI, overal_mean),
      y = c(1, 1.25, 1, 0.75),
      col = col
    )

  }else if(plot_type == "ggplot"){

    plot <- ggplot2::ggplot()

    # add the studies
    plot <- plot +ggplot2::geom_errorbar(
      mapping = ggplot2::aes(
        xmin   = posterior_data[posterior_data$y_uCI - posterior_data$y_lCI > 0,]$y_lCI,
        xmax   = posterior_data[posterior_data$y_uCI - posterior_data$y_lCI > 0,]$y_uCI,
        y      = posterior_data[posterior_data$y_uCI - posterior_data$y_lCI > 0,]$x),
      color   = col,
      width   = .25)
    plot <- plot +ggplot2::geom_point(
      mapping = ggplot2::aes(
        x    = posterior_data$y,
        y    = posterior_data$x,
        size = cex * posterior_data$post_prob),
      col   = col,
      shape = 15)

    if(prior){
      plot <- plot +ggplot2::geom_errorbar(
        mapping = ggplot2::aes(
          xmin   = prior_data[prior_data$y_uCI - prior_data$y_lCI > 0,]$y_lCI,
          xmax   = prior_data[prior_data$y_uCI - prior_data$y_lCI > 0,]$y_uCI,
          y      = prior_data[prior_data$y_uCI - prior_data$y_lCI > 0,]$x),
        color   = col2,
        width   = .25)
      plot <- plot +ggplot2::geom_point(
        mapping = ggplot2::aes(
          x    = prior_data$y,
          y    = prior_data$x,
          size = cex * prior_data$prior_prob),
        shape = 15,
        col   = col2)
    }

    # add the overall estimate
    plot <- plot + ggplot2::geom_polygon(
      mapping = ggplot2::aes(
        x = c(overal_lCI, overal_mean , overal_uCI, overal_mean),
        y = c(1, 1.25, 1, 0.75)),
      fill = col)

    # add the vertical line
    plot <- plot + ggplot2::geom_line(
      mapping = ggplot2::aes(
        x = c(vertical_0, vertical_0),
        y = ylim),
      linetype = "dotted")

    # add all the other stuff
    if(is.null(dots[["y_axis2"]]) || (!is.null(dots[["y_axis2"]]) && dots[["y_axis2"]])){
      plot <- plot + ggplot2::scale_y_continuous(
        name = "", breaks = y_at, labels = y_labels, limits = ylim,
        sec.axis = ggplot2::sec_axis( ~ ., breaks = y_at2, labels = y_labels2))
      attr(plot, "sec_axis") <- TRUE
    }else{
      plot <- plot + ggplot2::scale_y_continuous(
        name = "", breaks = y_at, labels = y_labels, limits = ylim)
      attr(plot, "sec_axis") <- FALSE
    }
    plot <- plot + ggplot2::scale_x_continuous(
      name = xlab, breaks = x_labels, labels = x_labels, limits = xlim)
    plot <- plot + ggplot2::theme(
      axis.title.y      = ggplot2::element_blank(),
      axis.line.y       = ggplot2::element_blank(),
      axis.ticks.y      = ggplot2::element_blank(),
      axis.text.y       = ggplot2::element_text(hjust = 0, color = "black"),
      axis.text.y.right = ggplot2::element_text(hjust = 1, color = "black"),
      legend.position   = "none")

  }

  return(plot)
}
