#' @title Plot samples from the marginal posterior distributions
#'
#' @param samples samples from a posterior distribution for a
#' parameter generated by [marginal_inference].
#' @param parameter parameter name to be plotted.
#' @param ... additional arguments
#' @inheritParams plot_posterior
#' @inheritParams density.prior
#' @inheritParams plot.prior
#'
#' @return \code{plot_marginal} returns either \code{NULL} or
#' an object of class 'ggplot' if plot_type is \code{plot_type = "ggplot"}.
#'
#' @details Marginal posterior vectors may carry a \code{posterior_density}
#' attribute with \code{x} and \code{y} coordinates. These densities are used
#' only when \code{density_method = "precomputed"}. Marginal KDE fallbacks use
#' a standard KDE because marginal prior-density grids are numerical density
#' ranges rather than true support metadata; this can intentionally differ from
#' the support-reflected ordinate used by \code{\link{Savage_Dickey_BF}} when
#' exact posterior-support metadata is available. If a stored density is used
#' and sample-derived point masses are available, the plot layer uses only
#' explicit \code{point_masses} from the stored density and warns when none are
#' declared.
#'
#' @seealso [prior()] [marginal_inference()]  [plot_posterior()]
#' @export
plot_marginal <- function(samples, parameter, plot_type = "base", prior = FALSE,
                          n_points = 1000,
                          transformation = NULL, transformation_arguments = NULL, transformation_settings = FALSE,
                          rescale_x = FALSE, par_name = NULL, dots_prior = list(),
                          legend = TRUE, legend_title = NULL, legend_labels = NULL, legend_position = NULL,
                          ..., density_method = c("KDE", "precomputed")){

  # check input
  if(any(!sapply(samples, inherits, what = "marginal_posterior")))
    stop("'samples' must be a be an object generated by 'marginal_posterior' function.")
  check_char(parameter, "parameter")
  check_char(plot_type, "plot_type", allow_values = c("base", "ggplot"))
  check_bool(legend, "legend", allow_NA = FALSE)
  density_method <- .posterior_density_method(density_method)
  .check_transformation_input(transformation, transformation_arguments, transformation_settings)


  # get the plotting range
  dots <- list(...)
  xlim <- dots[["xlim"]]


  plot_data <- .plot_data_marginal_samples(samples, parameter = parameter, prior = prior, n_points = n_points,
                                           transformation = transformation, transformation_arguments = transformation_arguments, transformation_settings = transformation_settings,
                                           density_method = density_method)



  # add priors, if requested
  if(prior){

    plot_data_prior <- unlist(lapply(plot_data, attr, which = "prior"), recursive = FALSE)

    # transplant common xlim and ylim
    plot_data_joined <- c(plot_data, plot_data_prior)

    xlim <- range(as.vector(sapply(plot_data_joined, attr, which = "x_range")))
    attr(plot_data_prior[[1]], "x_range") <- xlim

    xlim <- range(as.vector(sapply(plot_data_joined, attr, which = "y_range")))
    attr(plot_data_prior[[1]], "y_range") <- xlim

    dots_prior <- .transfer_dots(dots_prior, ...)


    # plot prior
    args_prior           <- dots_prior
    args_prior$plot_data <- plot_data_prior
    args_prior$plot_type <- plot_type
    args_prior$par_name  <- par_name
    args_prior$hardcode  <- TRUE
    args_prior$legend    <- FALSE
    args_prior$legend_title <- legend_title
    args_prior$legend_labels <- legend_labels
    args_prior$legend_position <- legend_position

    plot <- do.call(.plot_prior_list.factor, args_prior)


    # plot posterior
    args           <- list(...)
    args$plot_data <- plot_data
    args$plot_type <- plot_type
    args$par_name  <- par_name
    args$add       <- TRUE
    args$legend    <- legend
    args$legend_title <- legend_title
    args$legend_labels <- legend_labels
    args$legend_position <- legend_position

    if(plot_type == "base"){
      plot <- do.call(.plot_prior_list.factor, args)
    }else if(plot_type == "ggplot"){
      plot <- plot + do.call(.plot_prior_list.factor, args)
    }

  }else{

    # plot just posterior otherwise
    plot <- .plot_prior_list.factor(
      plot_data = plot_data, plot_type = plot_type, par_name = par_name,
      legend = legend, legend_title = legend_title, legend_labels = legend_labels,
      legend_position = legend_position, ...
    )

  }


  if(plot_type == "ggplot"){
    return(plot)
  }else{
    return(invisible())
  }

}

.plot_data_marginal_samples     <- function(samples, parameter, prior, n_points, transformation, transformation_arguments, transformation_settings,
                                            density_method = c("KDE", "precomputed")){

  check_list(samples, "samples", check_names = parameter, allow_other = TRUE)
  density_method <- .posterior_density_method(density_method)

  # extract the relevant information
  if(is.list(samples[[parameter]]) && length(samples[[parameter]]) > 1){
    posterior_samples <- .marginal_posterior_parameter_samples(samples, parameter)
    prior_densities   <- .marginal_posterior_parameter_prior_densities(samples, parameter)
    posterior_densities <- .marginal_posterior_parameter_posterior_densities(samples, parameter)
    if(prior){
      if(any(vapply(prior_densities, is.null, logical(1))))
        stop("'samples' did not contain prior densities")
    }
  }else{
    posterior_samples <- .marginal_posterior_parameter_samples(samples, parameter)
    prior_densities   <- .marginal_posterior_parameter_prior_densities(samples, parameter)
    posterior_densities <- .marginal_posterior_parameter_posterior_densities(samples, parameter)
    if(prior){
      if(is.null(prior_densities[[1]]))
        stop("'samples' did not contain prior densities")
    }
  }


  # create the output object
  out <- list()


  # deal with the densities
  for(i in seq_along(posterior_samples)){

    out_level <- .plot_data_marginal_samples.den(
      posterior_samples[[i]],
      n_points,
      transformation,
      transformation_arguments,
      transformation_settings,
      prior_density     = prior_densities[[i]],
      posterior_density = posterior_densities[[i]],
      density_method    = density_method
    )

    for(j in seq_along(out_level)){
      attr(out_level[[j]], "level")      <- i
      attr(out_level[[j]], "level_name") <- names(posterior_samples)[i]
    }

    if(prior){
      out_den.prior <- .prior_linear_density_to_plot_data(
        prior_densities[[i]],
        n_points                  = n_points,
        transformation            = transformation,
        transformation_arguments  = transformation_arguments,
        transformation_settings   = transformation_settings,
        factor                    = TRUE,
        level                     = i,
        level_name                = names(posterior_samples)[i]
      )

      attr(out_level[[1]], "prior") <- out_den.prior
    }

    for(j in seq_along(out_level)){
      out[[paste0(names(out_level)[j], i)]] <- out_level[[j]]
    }

  }

  return(out)
}
.plot_data_marginal_samples.den <- function(x, n_points, transformation, transformation_arguments, transformation_settings,
                                            prior_density = NULL, posterior_density = NULL,
                                            density_method = c("KDE", "precomputed")){

  point_locations <- .plot_data_marginal_samples_point_locations(prior_density)
  point_samples   <- rep(FALSE, length(x))
  x_points        <- NULL
  y_points        <- NULL
  density_method <- .posterior_density_method(density_method)
  posterior_density <- .posterior_density_for_method(posterior_density, density_method)

  if(length(point_locations) > 0){
    point_counts <- numeric(length(point_locations))
    for(i in seq_along(point_locations)){
      tol <- sqrt(.Machine$double.eps) * max(1, abs(point_locations[i]))
      point_matches <- !point_samples & abs(x - point_locations[i]) <= tol
      point_counts[i] <- sum(point_matches)
      point_samples <- point_samples | point_matches
    }

    point_keep <- point_counts > 0
    x_points <- point_locations[point_keep]
    y_points <- point_counts[point_keep] / length(x)
  }

  samples_density <- x[!point_samples]

  # create the output object
  out <- list()

  # get the density estimate
  if(!is.null(posterior_density)){
    sample_points_available <- !is.null(y_points)
    x_points <- NULL
    y_points <- NULL
    if(.posterior_density_point_masses_declared(posterior_density)){
      stored_points <- .plot_data_stored_point_masses(
        posterior_density
      )
      x_points <- stored_points[["x"]]
      y_points <- stored_points[["y"]]
    }else if(sample_points_available){
      .plot_data_warn_missing_stored_point_masses()
    }

    x_den <- posterior_density[["x"]]
    y_den <- posterior_density[["y"]]

    if(!is.null(transformation)){
      x_den           <- .density.prior_transformation_x(x_den, transformation, transformation_arguments)
      y_den           <- .density.prior_transformation_y(x_den, y_den, transformation, transformation_arguments)
      samples_density <- .density.prior_transformation_x(samples_density, transformation, transformation_arguments)
    }

    out_den <- list(
      call    = call("density", "stored posterior density"),
      bw      = NULL,
      n       = length(x_den),
      x       = x_den,
      y       = y_den,
      samples = samples_density
    )

    class(out_den) <- c("density", "density.prior", "density.prior.factor", "density.prior.simple")
    attr(out_den, "x_range")    <- range(x_den)
    attr(out_den, "y_range")    <- c(0, max(y_den))
    attr(out_den, "posterior_density_method") <- posterior_density[["method"]]
    attr(out_den, "posterior_density_diagnostics") <- posterior_density[["diagnostics"]]

    out[["density"]] <- out_den

  }else if(length(samples_density) > 1 && diff(range(samples_density)) > 0){
    args <- list(x = samples_density, n = n_points)

    density_continuous <- do.call(stats::density, args)
    x_den    <- density_continuous$x
    y_den    <- density_continuous$y * (length(samples_density) / length(x))

    # apply transformations
    if(!is.null(transformation)){
      x_den           <- .density.prior_transformation_x(x_den, transformation, transformation_arguments)
      y_den           <- .density.prior_transformation_y(x_den, y_den, transformation, transformation_arguments)
      samples_density <- .density.prior_transformation_x(samples_density, transformation, transformation_arguments)
    }

    out_den <- list(
      call    = call("density", "mixed samples"),
      bw      = NULL,
      n       = n_points,
      x       = x_den,
      y       = y_den,
      samples = samples_density
    )

    class(out_den) <- c("density", "density.prior", "density.prior.factor", "density.prior.simple")
    attr(out_den, "x_range")    <- range(x_den)
    attr(out_den, "y_range")    <- c(0, max(y_den))

    out[["density"]] <- out_den

  }else if(length(samples_density) > 0){
    x_points <- c(x_points, unique(samples_density))
    y_points <- c(y_points, tabulate(match(samples_density, unique(samples_density))) / length(x))
  }

  if(!is.null(y_points)){
    if(!is.null(transformation)){
      x_points <- .density.prior_transformation_x(x_points, transformation, transformation_arguments)
    }

    for(i in seq_along(y_points)){
      temp_points <- list(
        call    = call("density", paste0("point", i)),
        bw      = NULL,
        n       = n_points,
        x       = x_points[i],
        y       = y_points[i],
        samples = NULL
      )

      class(temp_points) <- c("density", "density.prior", "density.prior.point", "density.prior.factor")
      attr(temp_points, "x_range") <- range(x_points)
      attr(temp_points, "y_range") <- c(0, max(y_points))

      out[[paste0("points", i)]] <- temp_points
    }
  }

  return(out)
}
.plot_data_marginal_samples_point_locations <- function(prior_density){

  if(!inherits(prior_density, "prior_linear_density") || is.null(prior_density$points) || nrow(prior_density$points) == 0){
    return(numeric())
  }

  points <- prior_density$points
  points <- points[points$p > 0, , drop = FALSE]
  if(nrow(points) == 0){
    return(numeric())
  }

  points$x
}
