#' @title Create BayesTools ensemble summary tables
#'
#' @description Creates estimate summaries based on posterior
#' distributions created by [mix_posteriors], inference summaries
#' based on inference created by [ensemble_inference], or ensemble
#' summary/diagnostics based on a list of [models_inference] models
#' (or [marginal_inference] in case of [marginal_estimates_table]).
#'
#' @param samples posterior samples created by [mix_posteriors]. For
#' \code{ensemble_estimates_table()}, a sample vector or matrix may contain
#' missing draws only if it declares them as undefined through its
#' \code{undefined_draws} metadata (\code{posterior_metadata(x,
#' "undefined_draws") <- }; a single value for a vector, or values named by
#' column for a matrix), as set by [parameter_draws()] from the catalog's
#' \code{definedness} (\code{"correlation"} for original-scale random-effect
#' correlations, \code{"allocation_active"} for variance shares of gated
#' total-variance allocations). Such a row
#' is summarized over its defined draws and a table footnote reports their
#' share, e.g., "summarized over k of n draws where the correlation is
#' defined, i.e. both SDs are positive". Any other missing draw is an error.
#' @param inference model inference created by [ensemble_inference]
#' @param parameters character vector of parameters (or a
#' named list with of character vectors for summary and
#' diagnostics tables) specifying the parameters
#' (and their grouping) for the summary table
#' @param models list of [models_inference] model objects,
#' each of which containing a list of \code{priors}
#' and \code{inference} object, The \code{inference} must be a
#' named list with information about the model: model number
#' \code{m_number}, marginal likelihood \code{marglik}, prior and
#' posterior probability \code{prior_prob} and \code{post_prob},
#' inclusion Bayes factor \code{inclusion_BF}, and fit summary
#' generated by [runjags_estimates_table] for the diagnostics
#' table
#' @param probs quantiles for parameter estimates
#' @param logBF whether the Bayes factor should be on log scale. When model
#' inference objects store log-space inclusion Bayes factors, log-scale
#' values are taken from them, so they remain finite beyond the range of
#' natural-scale Bayes factors.
#' @param BF01 whether the Bayes factor should be inverted
#' @param short_name whether the prior distribution names should be
#' shortened. Defaults to \code{FALSE}.
#' @param remove_spike_0 whether prior distributions equal to spike
#' at 0 should be removed from the \code{prior_list}. In JAGS estimates
#' tables with \code{transform_scaled = TRUE}, a coefficient with a spike at
#' 0 is kept when it is non-zero on the original scale.
#' @param transform_factors whether factors with orthonormal/meandif
#' prior distribution should be transformed to differences from the
#' grand mean, and factors with [prior_ordered()] prior distribution to
#' their level effects (without the reference level of a \code{"cumulative"}
#' contrast, which is fixed at zero). Untransformed ordered factors show the
#' sampled parameters: \code{runjags_estimates_table()} reports the total
#' effect (\code{<term>_ordered_total}) and the allocation shares of the
#' random allocations (\code{<term>_ordered_allocation[<level>]}, the share
#' of the total added when reaching \code{<level>}; fixed allocations have no
#' rows). \code{ensemble_estimates_table()} reports retained fitted totals and
#' the union of allocation shares sampled by any declared ordered model.
#' Fixed ordered allocations fill that union with their declared constants.
#' Models without the ordered parameterization have undefined (\code{NA})
#' shares, with their defined fraction reported in a footnote. Shares remain
#' defined on zero-total and excluded spike draws of an ordered model. Legacy
#' mixed objects without retained sources must be recreated from source fits.
#' @param transform_scaled whether coefficients from standardized
#' continuous predictors should be transformed back to the original
#' scale. For \code{runjags_estimates_table()}, random-effect summaries are
#' also derived on the transformed scale when the fit contains
#' \code{formula_scale} metadata: random-effect SDs and correlations are
#' computed from the transformed covariance draws. Mixed posterior samples are
#' transformed through the fitted design of \code{formula_scale}: every column
#' is mapped to its fitted coefficient by its \code{quantities} draw metadata
#' (see [posterior_metadata()]), and columns that are not fitted coefficients
#' are refused, as are random-effect SDs that the random-effect structure of
#' \code{formula_scale} does not cover (SDs it does not contain, blocks it
#' contains only in part, or blocks it leaves unchanged while the samples'
#' original-scale SDs differ from the fitted ones). The SD columns of a block
#' with a standardized random slope are labelled by their fitted coordinates
#' (\code{(mu) g: sd(x)}) until they are transformed to the catalog's
#' original-scale SDs. Estimated marginal means of [marginal_estimates_table()] are
#' predictions at the stated predictor values, which do not depend on the
#' standardization, and are not changed. Defaults to \code{FALSE}.
#' @param formula_scale named list containing standardization information
#' (mean and sd) for each standardized predictor, together with the fitted
#' design of each formula: the \code{formula_scale} attribute of the fitted
#' model. Required when \code{transform_scaled = TRUE} for ensemble/marginal
#' tables; standardization information without the fitted design stops with a
#' \code{BayesTools_formula_transform_unavailable} error. For
#' \code{runjags_estimates_table}, this is automatically extracted from
#' the fit object's \code{formula_scale} attribute.
#' @param title title to be added to the table
#' @param footnotes footnotes to be added to the table
#' @param warnings warnings to be added to the table
#' @param formula_prefix whether the parameter prefix from formula should
#' be printed. Defaults to \code{TRUE}.
#'
#'
#' @return \code{ensemble_estimates_table} returns a table with the
#' model-averaged estimates, \code{ensemble_inference_table} returns
#' a table with the prior and posterior probabilities and inclusion
#' Bayes factors, \code{ensemble_summary_table} returns a table with
#' overview of the models included in the ensemble, and
#' \code{ensemble_diagnostics_table} returns an overview of the MCMC
#' diagnostics for the models included in the ensemble. All of the
#' tables are objects of class 'BayesTools_table'. The estimates tables
#' (\code{ensemble_estimates_table} and \code{marginal_estimates_table})
#' carry the per-row quantity table \code{attr(table, "quantities")}: a data
#' frame with one row per table row and the columns \code{row} (the row
#' label), \code{quantity_id} (the [parameter_catalog()] quantity id the
#' summarized draws declare in their \code{quantities} metadata, see
#' [posterior_metadata()]; \code{""} when they declare none, e.g. for
#' estimated marginal means), and \code{label_parts} (the label parts the row
#' label is rendered from; see [parameter_labels()]). Subsetting the table
#' subsets its quantity table.
#'
#' @export ensemble_estimates_table
#' @export ensemble_inference_table
#' @export ensemble_summary_table
#' @export ensemble_diagnostics_table
#' @export ensemble_estimates_empty_table
#' @export ensemble_inference_empty_table
#' @export ensemble_summary_empty_table
#' @export ensemble_diagnostics_empty_table
#' @export marginal_estimates_table
#' @name BayesTools_ensemble_tables
#'
#' @seealso [ensemble_inference] [mix_posteriors] [BayesTools_model_tables]
NULL

#' @rdname BayesTools_ensemble_tables
ensemble_estimates_table <- function(samples, parameters, probs = c(0.025, 0.975), title = NULL, footnotes = NULL, warnings = NULL, transform_factors = FALSE, formula_prefix = TRUE, transform_scaled = FALSE, formula_scale = NULL){

  # check input
  check_char(parameters, "parameters", check_length = 0)
  check_list(samples, "samples", check_names = parameters, all_objects = TRUE, allow_other = TRUE)
  check_real(probs, "probs", lower = 0, upper = 1, check_length = 0, allow_NULL = TRUE)
  check_char(title, "title", allow_NULL = TRUE)
  check_char(footnotes, "footnotes", check_length = 0, allow_NULL = TRUE)
  check_char(warnings, "warnings", check_length = 0, allow_NULL = TRUE)
  check_bool(transform_factors, "transform_factors")
  check_bool(formula_prefix, "formula_prefix")
  check_bool(transform_scaled, "transform_scaled")
  check_list(formula_scale, "formula_scale", allow_NULL = TRUE)

  # declared possibly undefined draws ('undefined_draws' metadata), captured
  # before transformations that may rebuild the sample objects
  undefined_draws <- lapply(parameters, function(parameter){
    .bt_meta_get(samples[[parameter]], "undefined_draws")
  })
  names(undefined_draws) <- parameters


  # transform scaled coefficients back to original scale
  transformed_scale <- transform_scaled && !is.null(formula_scale) &&
    length(formula_scale) > 0
  if(transformed_scale){
    samples <- .transform_scale_samples_list(samples, formula_scale)
  }

  # transform meandif/orthonormal/ordered posterior (without the reference
  # level of a cumulative ordered contrast, which is fixed at zero)
  if(transform_factors){
    samples <- transform_factor_samples(samples)
    for(parameter in parameters){
      if(inherits(samples[[parameter]], "mixed_posteriors.ordered_transformed")){
        samples[[parameter]] <- .transformed_factor_drop_structural_levels(samples[[parameter]])
      }
    }
  }
  if(!transform_factors){
    for(parameter in parameters){
      if(isTRUE(attr(samples[[parameter]], "ordered", exact = TRUE))){
        raw <- .bt_ordered_raw_table_samples(samples[[parameter]])
        if(is.null(raw)){
          footnotes <- c(footnotes, "Raw ordered decomposition is unavailable for models with a different nonzero parameterization; coefficient rows are shown.")
        }else{
          samples[[parameter]] <- raw
          undefined_draws[[parameter]] <- .bt_meta_get(raw, "undefined_draws")
          if(transformed_scale || isTRUE(.bt_meta_get(samples,"transform_scaled"))){
            footnotes <- c(footnotes,.bt_ordered_fitted_scale_footnote())
          }
        }
      }
    }
  }

  # row labels rendered from the label parts of every column (recorded with
  # the columns' quantity ids for the table's 'quantities')
  row_parts <- list()
  row_quantity_ids <- character()
  row_labels <- function(parameter){
    parts <- .bt_draws_label_parts(samples[[parameter]], parameter)
    if(transformed_scale){
      parts <- .bt_label_parts_log_intercept(parts, formula_scale)
    }
    quantities <- .bt_draws_quantities(samples[[parameter]])
    row_parts <<- c(row_parts, parts)
    row_quantity_ids <<- c(
      row_quantity_ids,
      if(is.null(quantities)) rep("", length(parts)) else quantities$quantity_id
    )
    .bt_label(parts, style = "table", formula_prefix = formula_prefix)
  }


  # extract values
  estimates_table <- NULL
  undefined_footnotes <- NULL
  for(parameter in parameters){

    if(is.matrix(samples[[parameter]])){

      parameter_name <- row_labels(parameter)

      par_summary <- NULL
      for(column in seq_len(ncol(samples[[parameter]]))){
        column_name <- colnames(samples[[parameter]])[column]
        defined <- .bt_ensemble_defined_draws(
          values = samples[[parameter]][, column],
          label  = if(is.null(column_name)) parameter else column_name,
          reason = .bt_ensemble_undefined_draws_reason(
            undefined_draws[[parameter]],
            column_name
          )
        )
        par_summary <- rbind(par_summary, .bt_ensemble_draw_summary(defined$values, probs))
        if(defined$n_defined < defined$n_draws){
          undefined_footnotes <- c(undefined_footnotes, .bt_undefined_draws_footnote(
            row       = if(is.null(parameter_name)) parameter else parameter_name[column],
            n_defined = defined$n_defined,
            n_draws   = defined$n_draws,
            reason    = defined$reason
          ))
        }
      }

      rownames(par_summary) <- parameter_name
      estimates_table       <- rbind(estimates_table, par_summary)

    }else if(is.numeric(samples[[parameter]])){

      parameter_name <- row_labels(parameter)

      defined <- .bt_ensemble_defined_draws(
        values = samples[[parameter]],
        label  = parameter,
        reason = .bt_ensemble_undefined_draws_reason(undefined_draws[[parameter]])
      )
      par_summary <- .bt_ensemble_draw_summary(defined$values, probs)
      estimates_table <- rbind(estimates_table, par_summary)

      rownames(estimates_table)[nrow(estimates_table)] <- parameter_name
      if(defined$n_defined < defined$n_draws){
        undefined_footnotes <- c(undefined_footnotes, .bt_undefined_draws_footnote(
          row       = parameter_name,
          n_defined = defined$n_defined,
          n_draws   = defined$n_draws,
          reason    = defined$reason
        ))
      }


    }else{
      stop("Uknown parameter type.")
    }
  }

  # prepare output
  estimates_table                    <- data.frame(estimates_table, check.names = FALSE)
  class(estimates_table)             <- c("BayesTools_table", "BayesTools_ensemble_summary", class(estimates_table))
  attr(estimates_table, "type")      <- rep("estimate", ncol(estimates_table))
  attr(estimates_table, "quantities") <- .bt_table_quantities(
    rows         = rownames(estimates_table),
    label_parts  = row_parts,
    quantity_ids = row_quantity_ids
  )
  attr(estimates_table, "rownames")  <- TRUE
  attr(estimates_table, "title")     <- title
  attr(estimates_table, "footnotes") <- c(footnotes, undefined_footnotes)
  attr(estimates_table, "warnings")  <- warnings

  return(estimates_table)
}

.bt_ensemble_draw_summary <- function(values, probs){

  quantiles <- vapply(
    probs,
    function(prob) unname(stats::quantile(values, probs = prob)),
    numeric(1)
  )
  names(quantiles) <- probs

  c("Mean" = mean(values), "Median" = stats::median(values), quantiles)
}

# The 'undefined_draws' declaration of one sample column: a scalar applies to
# every column; a named vector is looked up by column name.
.bt_ensemble_undefined_draws_reason <- function(declaration, column = NULL){

  if(is.null(declaration) || length(declaration) == 0L){
    return(NULL)
  }
  if(!is.null(column) && !is.null(names(declaration)) &&
     any(nzchar(names(declaration)))){
    if(!column %in% names(declaration)){
      return(NULL)
    }
    return(declaration[[column]])
  }
  if(length(declaration) != 1L){
    stop(
      "An 'undefined_draws' declaration of a sample vector must be a single ",
      "value.",
      call. = FALSE
    )
  }

  declaration[[1L]]
}

# Missing draws are accepted only for a quantity declared as possibly
# undefined; the summary then uses its defined draws. Any other missing draw
# signals an error upstream.
.bt_ensemble_defined_draws <- function(values, label, reason = NULL){

  missing <- is.na(values)
  if(any(missing) && is.null(reason)){
    stop(
      "The posterior draws of '", label, "' contain missing values. Missing ",
      "draws are accepted only for quantities declared as possibly undefined ",
      "(draw metadata 'undefined_draws', set by parameter_draws() or with ",
      "posterior_metadata()).",
      call. = FALSE
    )
  }
  if(any(missing)){
    # validates the declaration
    .bt_undefined_draws_footnote(label, 0L, 0L, reason)
  }

  list(
    values    = as.numeric(values[!missing]),
    n_defined = sum(!missing),
    n_draws   = length(values),
    reason    = reason
  )
}

#' @rdname BayesTools_ensemble_tables
ensemble_inference_table <- function(inference, parameters, logBF = FALSE, BF01 = FALSE, title = NULL, footnotes = NULL, warnings = NULL){

  # check input
  check_char(parameters, "parameters", check_length = 0)
  check_list(inference, "inference", check_names = parameters, all_objects = TRUE, allow_other = TRUE)
  check_bool(logBF, "logBF", allow_NA = FALSE)
  check_bool(BF01,  "BF01",  allow_NA = FALSE)
  check_char(title, "title", allow_NULL = TRUE)
  check_char(footnotes, "footnotes", check_length = 0, allow_NULL = TRUE)
  check_char(warnings, "warnings", check_length = 0, allow_NULL = TRUE)
  conditional <- attr(inference, "conditional", exact = TRUE)
  if(!is.null(conditional)){
    check_bool(conditional, "attr(inference, \"conditional\")", allow_NA = FALSE)
  }
  if(isTRUE(conditional))
    stop("The inference object cannot be 'conditional'.")

  # extract values
  inference_table <- NULL
  n_models        <- NULL
  log_BF          <- NULL
  for(parameter in parameters){
    parameter_inference <- inference[[parameter]]
    if(inherits(parameter_inference, "inference") ||
       !is.null(attr(parameter_inference, "model_probability_declaration", exact = TRUE))){
      .model_probability_inference_get(parameter_inference, "prior")
      .model_probability_inference_get(parameter_inference, "posterior")
    }
    is_null <- attr(parameter_inference, "is_null", exact = TRUE)
    if(is.null(is_null) || !is.logical(is_null)){
      stop(
        "The inference object for parameter '", parameter,
        "' must have a logical 'is_null' attribute.",
        call. = FALSE
      )
    }
    check_real(parameter_inference[["prior_probs"]], paste0("inference$", parameter, "$prior_probs"), lower = 0, upper = 1, check_length = length(is_null), allow_NA = FALSE)
    check_real(parameter_inference[["post_probs"]], paste0("inference$", parameter, "$post_probs"), lower = 0, upper = 1, check_length = length(is_null), allow_NA = FALSE)
    check_real(parameter_inference[["BF"]], paste0("inference$", parameter, "$BF"), lower = 0, check_length = 1, allow_NA = TRUE)
    parameter_name <- attr(parameter_inference, "parameter_name", exact = TRUE)
    if(is.null(parameter_name)){
      parameter_name <- parameter
    }else{
      check_char(parameter_name, paste0("attr(inference$", parameter, ", \"parameter_name\")"), check_length = 1, allow_NA = FALSE)
    }
    inference_table <- rbind(inference_table, c(
      "models"       = sum(!is_null),
      "prior_prob"   = sum(parameter_inference[["prior_probs"]][!is_null]),
      "post_prob"    = sum(parameter_inference[["post_probs"]][!is_null]),
      "inclusion_BF" = parameter_inference[["BF"]]
    ))
    rownames(inference_table)[nrow(inference_table)] <- parameter_name
    n_models <- c(n_models, length(is_null))
    log_BF   <- c(log_BF, .ensemble_log_BF(
      BF     = parameter_inference[["BF"]],
      log_BF = attr(parameter_inference, "log_BF", exact = TRUE),
      name   = paste0("attr(inference$", parameter, ", \"log_BF\")")
    ))
  }
  inference_table <- data.frame(inference_table)

  # format BF (log-scale output from the log-space Bayes factor)
  inference_table[,"inclusion_BF"]  <- .format_BF_from_log(
    log_BF,
    logBF     = logBF,
    BF01      = BF01,
    inclusion = TRUE,
    BF        = inference_table[,"inclusion_BF"]
  )

  # prepare output
  class(inference_table)             <- c("BayesTools_table", "BayesTools_ensemble_summary", class(inference_table))
  attr(inference_table, "type")      <- c("n_models", "prior_prob", "post_prob", "inclusion_BF")
  attr(inference_table, "rownames")  <- TRUE
  attr(inference_table, "n_models")  <- n_models
  attr(inference_table, "title")     <- title
  attr(inference_table, "footnotes") <- footnotes
  attr(inference_table, "warnings")  <- warnings

  return(inference_table)
}

# Natural-log inclusion Bayes factor of one table row. Inference objects keep
# the log-space value as an attribute; objects without it use log(BF).
.ensemble_log_BF <- function(BF, log_BF, name){

  if(is.null(log_BF)){
    return(log(as.numeric(BF)))
  }
  check_real(log_BF, name, check_length = 1, allow_NA = TRUE)

  as.numeric(log_BF)
}

#' @rdname BayesTools_ensemble_tables
ensemble_summary_table <- function(models, parameters, logBF = FALSE, BF01 = FALSE, title = NULL, footnotes = NULL, warnings = NULL,
                                   remove_spike_0 = TRUE, short_name = FALSE){

  # check input
  check_list(models, "models")
  for(i in seq_along(models)){
    model <- models[[i]]
    check_list(model, "model", check_names = "inference", allow_other = TRUE, all_objects = TRUE)
    prior_list <- attr(model[["fit"]], "prior_list")
    check_list(prior_list, "model:priors")
    if(!all(sapply(prior_list, is.prior)))
      stop("'model:priors' must be a list of priors.")
    model_inference <- model[["inference"]]
    .model_probability_scalar_inference_validate(model_inference)
    check_list(model_inference, "model:inference", check_names = c("m_number", "marglik", "prior_prob", "post_prob", "inclusion_BF"), allow_other = TRUE, all_objects = TRUE)
    check_int(model_inference[["m_number"]],      "model_inference:model_number")
    check_real(model_inference[["marglik"]],      "model_inference:marglik")
    check_real(model_inference[["prior_prob"]],   "model_inference:prior_prob",   lower = 0, upper = 1)
    check_real(model_inference[["post_prob"]],    "model_inference:post_prob",   lower = 0, upper = 1)
    check_real(model_inference[["inclusion_BF"]], "model_inference:inclusion_BF", lower = 0)
  }
  if(is.list(parameters)){
    check_list(parameters, "parameters")
    check_char(names(parameters), "names(parameters)", check_length = FALSE, allow_NULL = length(parameters) == 0)
    sapply(parameters, check_char, name = "parameters", check_length = FALSE)
  }else{
    check_char(parameters, "parameters", check_length = FALSE)
    if(is.null(names(parameters))){
      names(parameters) <- parameters
    }
  }
  check_bool(logBF, "logBF", allow_NA = FALSE)
  check_bool(BF01,  "BF01",  allow_NA = FALSE)
  check_char(title, "title", allow_NULL = TRUE)
  check_char(footnotes, "footnotes", check_length = 0, allow_NULL = TRUE)
  check_char(warnings, "warnings", check_length = 0, allow_NULL = TRUE)
  check_bool(remove_spike_0, "remove_spike_0", allow_NA = FALSE)
  check_bool(short_name, "short_name", allow_NA = FALSE)


  # create the output
  ensemble_table <- .ensemble_table_foundation(models, parameters, remove_spike_0, short_name)

  ensemble_table <- cbind(
    ensemble_table,
    "prior_prob"   = sapply(models, function(model)model[["inference"]][["prior_prob"]]),
    "marglik"      = sapply(models, function(model)model[["inference"]][["marglik"]]),
    "post_prob"    = sapply(models, function(model)model[["inference"]][["post_prob"]]),
    "inclusion_BF" = sapply(models, function(model)model[["inference"]][["inclusion_BF"]])
  )

  # format BF (log-scale output from the log-space Bayes factor)
  log_BF <- vapply(seq_along(models), function(i){
    .ensemble_log_BF(
      BF     = models[[i]][["inference"]][["inclusion_BF"]],
      log_BF = attr(models[[i]][["inference"]], "inclusion_log_BF", exact = TRUE),
      name   = paste0("attr(models[[", i, "]]$inference, \"inclusion_log_BF\")")
    )
  }, numeric(1))
  ensemble_table[,"inclusion_BF"]  <- .format_BF_from_log(
    log_BF,
    logBF     = logBF,
    BF01      = BF01,
    inclusion = TRUE,
    BF        = ensemble_table[,"inclusion_BF"]
  )

  # prepare output
  class(ensemble_table)             <- c("BayesTools_table", "BayesTools_ensemble_summary", class(ensemble_table))
  attr(ensemble_table, "type")      <- c("integer", rep("prior", length(parameters)), "prior_prob", "marglik", "post_prob", "inclusion_BF")
  attr(ensemble_table, "rownames")  <- FALSE
  attr(ensemble_table, "title")     <- title
  attr(ensemble_table, "footnotes") <- footnotes
  attr(ensemble_table, "warnings")  <- warnings

  return(ensemble_table)
}

#' @rdname BayesTools_ensemble_tables
ensemble_diagnostics_table <- function(models, parameters, title = NULL, footnotes = NULL, warnings = NULL, remove_spike_0 = TRUE, short_name = FALSE){

  # check input
  check_list(models, "models")
  for(i in seq_along(models)){
    model <- models[[i]]
    check_list(model, "model", check_names = c("fit_summary", "inference"), allow_other = TRUE, all_objects = TRUE)
    prior_list <- attr(model[["fit"]], "prior_list")
    check_list(prior_list, "model:priors")
    if(!all(sapply(prior_list, is.prior)))
      stop("'model:priors' must be a list of priors.")
    if(!is.null(model[["fit_summary"]]) && !(inherits(model[["fit_summary"]], "BayesTools_runjags_summary") || inherits(model[["fit_summary"]], "BayesTools_stan_summary")))
      stop("'fit_summary' must be a runjags or rstan summary generated by 'JAGS_estimates_table()' / 'stan_estimates_table()'.")
    model_inference <- model[["inference"]]
    check_list(model_inference, "model:inference", check_names = "m_number", allow_other = TRUE, all_objects = TRUE)
    check_int(model_inference[["m_number"]], "model_inference:model_number")
  }
  if(is.list(parameters)){
    check_list(parameters, "parameters")
    check_char(names(parameters), "names(parameters)", check_length = FALSE, allow_NULL = length(parameters) == 0)
    sapply(parameters, check_char, name = "parameters", check_length = FALSE)
  }else{
    check_char(parameters, "parameters", check_length = FALSE)
    if(is.null(names(parameters))){
      names(parameters) <- parameters
    }
  }
  check_char(title, "title", allow_NULL = TRUE)
  check_char(footnotes, "footnotes", check_length = 0, allow_NULL = TRUE)
  check_char(warnings, "warnings", check_length = 0, allow_NULL = TRUE)
  check_bool(remove_spike_0, "remove_spike_0", allow_NA = FALSE)
  check_bool(short_name, "short_name", allow_NA = FALSE)

  # create the output
  ensemble_table <- .ensemble_table_foundation(models, parameters, remove_spike_0, short_name)

  ensemble_table <- cbind(
    ensemble_table,
    "max_MCMC_error"    = sapply(models, function(model){
      .max_or_na(.fit_summary_column(model[["fit_summary"]], "MCMC_error"))
    }),
    "max_MCMC_SD_error" = sapply(models, function(model){
      .max_or_na(.fit_summary_column(model[["fit_summary"]], "MCMC_SD_error"))
    }),
    "min_ESS"     = sapply(models, function(model){
      .min_or_na(.fit_summary_column(model[["fit_summary"]], "ESS"))
    }),
    "max_R_hat"   = sapply(models, function(model){
      .max_or_na(.fit_summary_column(model[["fit_summary"]], "R_hat"))
    })
  )

  # prepare output
  class(ensemble_table)             <- c("BayesTools_table", "BayesTools_ensemble_summary", class(ensemble_table))
  attr(ensemble_table, "type")      <- c("integer", rep("prior", length(parameters)), "max_MCMC_error", "max_MCMC_SD_error", "min_ESS", "max_R_hat")
  attr(ensemble_table, "rownames")  <- FALSE
  attr(ensemble_table, "title")     <- title
  attr(ensemble_table, "footnotes") <- footnotes
  attr(ensemble_table, "warnings")  <- warnings

  return(ensemble_table)
}

#' @rdname BayesTools_ensemble_tables
ensemble_estimates_empty_table   <- function(probs = c(0.025, 0.975), title = NULL, footnotes = NULL, warnings = NULL){

  empty_table <- data.frame(matrix(nrow = 0, ncol = 2 + length(probs)))
  colnames(empty_table) <- c("Mean", "Median", probs)

  class(empty_table)             <- c("BayesTools_table", "BayesTools_ensemble_summary", class(empty_table))
  attr(empty_table, "type")      <- rep("estimate", ncol(empty_table))
  attr(empty_table, "rownames")  <- TRUE
  attr(empty_table, "title")     <- title
  attr(empty_table, "footnotes") <- footnotes
  attr(empty_table, "warnings")  <- warnings

  return(empty_table)
}

#' @rdname BayesTools_ensemble_tables
ensemble_inference_empty_table   <- function(title = NULL, footnotes = NULL, warnings = NULL){

  empty_table <- data.frame(matrix(nrow = 0, ncol = 4))
  colnames(empty_table) <- c("models", "prior_prob", "post_prob", "inclusion_BF")

  class(empty_table)             <- c("BayesTools_table", "BayesTools_ensemble_summary", class(empty_table))
  attr(empty_table, "type")      <- c("n_models", "prior_prob", "post_prob", "inclusion_BF")
  attr(empty_table, "rownames")  <- TRUE
  attr(empty_table, "title")     <- title
  attr(empty_table, "footnotes") <- footnotes
  attr(empty_table, "warnings")  <- warnings

  return(empty_table)
}

#' @rdname BayesTools_ensemble_tables
ensemble_summary_empty_table     <- function(title = NULL, footnotes = NULL, warnings = NULL){

  empty_table <- data.frame(matrix(nrow = 0, ncol = 5))
  colnames(empty_table) <- c("Model", "prior_prob", "marglik", "post_prob", "inclusion_BF")

  # prepare output
  class(empty_table)             <- c("BayesTools_table", "BayesTools_ensemble_summary", class(empty_table))
  attr(empty_table, "type")      <- c("integer", "prior_prob", "marglik", "post_prob", "inclusion_BF")
  attr(empty_table, "rownames")  <- FALSE
  attr(empty_table, "title")     <- title
  attr(empty_table, "footnotes") <- footnotes
  attr(empty_table, "warnings")  <- warnings

  return(empty_table)
}

#' @rdname BayesTools_ensemble_tables
ensemble_diagnostics_empty_table <- function(title = NULL, footnotes = NULL, warnings = NULL){

  empty_table <- data.frame(matrix(nrow = 0, ncol = 5))
  colnames(empty_table) <- c("Model", "max_MCMC_error", "max_MCMC_SD_error", "min_ESS", "max_R_hat")

  # prepare output
  class(empty_table)             <- c("BayesTools_table", "BayesTools_ensemble_summary", class(empty_table))
  attr(empty_table, "type")      <- c("integer", "max_MCMC_error", "max_MCMC_SD_error", "min_ESS", "max_R_hat")
  attr(empty_table, "rownames")  <- FALSE
  attr(empty_table, "title")     <- title
  attr(empty_table, "footnotes") <- footnotes
  attr(empty_table, "warnings")  <- warnings

  return(empty_table)
}

#' @rdname BayesTools_ensemble_tables
marginal_estimates_table <- function(samples, inference, parameters, probs = c(0.025, 0.5, 0.975), logBF = FALSE, BF01 = FALSE, title = NULL, footnotes = NULL, warnings = NULL, formula_prefix = TRUE, transform_scaled = FALSE, formula_scale = NULL){

  # check input
  check_char(parameters, "parameters", check_length = 0)
  check_list(samples, "samples", check_names = parameters, all_objects = TRUE, allow_other = TRUE)
  check_list(inference, "inference", check_names = parameters, all_objects = TRUE, allow_other = TRUE)
  check_real(probs, "probs", lower = 0, upper = 1, check_length = 0, allow_NULL = TRUE)
  check_bool(logBF, "logBF", allow_NA = FALSE)
  check_bool(BF01,  "BF01",  allow_NA = FALSE)
  check_char(title, "title", allow_NULL = TRUE)
  check_char(footnotes, "footnotes", check_length = 0, allow_NULL = TRUE)
  check_char(warnings, "warnings", check_length = 0, allow_NULL = TRUE)
  check_bool(formula_prefix, "formula_prefix")
  check_bool(transform_scaled, "transform_scaled")
  check_list(formula_scale, "formula_scale", allow_NULL = TRUE)

  # transform scaled coefficients back to original scale
  if(transform_scaled && !is.null(formula_scale) && length(formula_scale) > 0){
    samples <- .transform_scale_samples_list(samples, formula_scale)
  }


  # extract values
  estimates_table <- NULL
  row_parts <- list()
  row_quantity_ids <- character()
  row_log_BF <- numeric()
  row_diagnostics <- list()
  for(parameter in parameters){

    # the label parts of every level: rows and warnings are rendered from them
    level_parts  <- .bt_marginal_level_parts(samples[[parameter]], parameter)
    level_labels <- .bt_label(level_parts, style = "table", formula_prefix = formula_prefix)
    row_parts <- c(row_parts, level_parts)
    row_quantity_ids <- c(row_quantity_ids, .bt_marginal_level_quantity_ids(samples[[parameter]]))
    level_warning_labels <- .bt_label(level_parts, style = "warning", formula_prefix = formula_prefix)

    # extract the relevant information
    if(is.list(samples[[parameter]]) && length(samples[[parameter]]) > 1){
      temp_samples  <- .marginal_posterior_parameter_samples(samples, parameter)
      temp_BF       <- do.call(c, inference[[parameter]])
      temp_BF_error <- .marginal_inference_BF_error_percent(inference[[parameter]], temp_BF)
      # the warnings of each level are keyed by that level
      warning_levels <- if(!is.null(names(inference[[parameter]])) &&
                           !is.null(names(samples[[parameter]]))){
        match(names(inference[[parameter]]), names(samples[[parameter]]))
      }else{
        seq_along(inference[[parameter]])
      }
      temp_warnings <- do.call(c, lapply(seq_along(inference[[parameter]]), function(lvl) {
        if(is.null(attr(inference[[parameter]][[lvl]], "warnings"))){
          return()
        }else{
          paste0(level_warning_labels[[warning_levels[[lvl]]]], ": ", attr(inference[[parameter]][[lvl]], "warnings"))
        }
      }))
    }else{
      temp_samples  <- .marginal_posterior_parameter_samples(samples, parameter)
      # a scalar Savage-Dickey BF keeps its attributes only when not subset
      temp_BF       <- if(is.list(inference[[parameter]])) inference[[parameter]][[1]] else inference[[parameter]]
      temp_BF_error <- .marginal_inference_BF_error_percent(inference[[parameter]], temp_BF)
      if(is.null(attr(temp_BF, "warnings"))){
        temp_warnings <- NULL
      }else{
        temp_warnings <- paste0(level_warning_labels[[1L]], ": ", attr(temp_BF, "warnings"))
      }
    }

    producers <- if(is.list(samples[[parameter]]) && length(samples[[parameter]]) > 1L){
      inference[[parameter]]
    }else list(temp_BF)
    row_log_BF <- c(row_log_BF, vapply(producers, function(value){
      logs <- .BF_carrier_log(value)
      if(is.null(logs)) log(as.numeric(value)) else logs
    }, numeric(1)))
    row_diagnostics <- c(row_diagnostics, lapply(producers, function(value) attr(value, "numerical_diagnostics")))
    # add estimates
    par_summary <- cbind(
      "Mean" = vapply(temp_samples, mean, numeric(1)),
      "SD"   = vapply(temp_samples, stats::sd, numeric(1))
    )
    for(i in seq_along(probs)){
      par_summary <- cbind(par_summary, vapply(temp_samples, stats::quantile, numeric(1), probs = probs[i]))
      colnames(par_summary)[ncol(par_summary)] <- probs[i]
    }

    # add BF
    par_summary <- cbind(
      par_summary,
      "inclusion_BF"     = temp_BF,
      "BF_error_percent" = temp_BF_error
    )


    rownames(par_summary) <- level_labels
    estimates_table       <- rbind(estimates_table, par_summary)

    # add warnings
    if(!is.null(temp_warnings)){
      warnings <- c(warnings, temp_warnings)
    }
  }

  # prepare output
  estimates_table                    <- data.frame(estimates_table, check.names = FALSE)
  has_BF_error                       <- any(is.finite(estimates_table[["BF_error_percent"]]))
  if(!has_BF_error){
    estimates_table[["BF_error_percent"]] <- NULL
  }
  estimates_table[["inclusion_BF"]] <- .format_BF_from_log(row_log_BF,
    logBF = logBF, BF01 = BF01, inclusion = TRUE,
    BF = estimates_table[["inclusion_BF"]], diagnostics = row_diagnostics)
  attr(estimates_table, "raw_log_BF") <- row_log_BF
  attr(estimates_table, "numerical_diagnostics") <- row_diagnostics
  if(has_BF_error){
    attr(estimates_table[["BF_error_percent"]], "name") <- .BF_error_column_name(BF01)
  }
  class(estimates_table)             <- c("BayesTools_table", "BayesTools_marginal_estimates", class(estimates_table))
  table_type                         <- rep("estimate", ncol(estimates_table))
  table_type[colnames(estimates_table) == "inclusion_BF"] <- "inclusion_BF"
  table_type[colnames(estimates_table) == "BF_error_percent"] <- "BF_error"
  attr(estimates_table, "type")      <- table_type
  attr(estimates_table, "quantities") <- .bt_table_quantities(
    rows         = rownames(estimates_table),
    label_parts  = row_parts,
    quantity_ids = row_quantity_ids
  )
  attr(estimates_table, "rownames")  <- TRUE
  attr(estimates_table, "title")     <- title
  attr(estimates_table, "footnotes") <- footnotes
  attr(estimates_table, "warnings")  <- warnings

  return(estimates_table)
}

# The quantity ids the levels of a marginal posterior declare ("" for levels
# without a column table, and for estimated marginal means).
.bt_marginal_level_quantity_ids <- function(x){

  levels <- if(is.list(x) && !is.numeric(x)) x else list(x)
  vapply(levels, function(level){
    quantities <- .bt_draws_quantities(level)
    if(is.null(quantities)) "" else quantities$quantity_id[[1L]]
  }, character(1), USE.NAMES = FALSE)
}

.marginal_inference_BF_error_percent <- function(inference, BF){

  out <- rep(NA_real_, length(BF))
  names(out) <- names(BF)
  if(length(out) == 0L){
    return(out)
  }

  if(is.list(inference) && !inherits(inference, "marginal_inference")){
    errors <- vapply(inference, .BF_error_percent_value, numeric(1))
    if(length(errors) == length(out)){
      out <- errors
      names(out) <- names(BF)
    }else if(!is.null(names(out)) && !is.null(names(errors))){
      out[] <- errors[names(out)]
    }
  }else{
    if(is.list(inference)){
      out[] <- .BF_error_percent_value(inference[[1]])
    }else{
      out[] <- .BF_error_percent_value(inference)
    }
  }

  return(out)
}

.BF_error_percent_value <- function(x){

  BF_error_percent <- attr(x, "BF_error_percent")
  if(is.null(BF_error_percent)){
    return(NA_real_)
  }

  BF_error_percent <- as.numeric(BF_error_percent)[1]
  if(!is.finite(BF_error_percent) || BF_error_percent < 0){
    return(NA_real_)
  }

  return(BF_error_percent)
}



.ensemble_table_foundation <- function(models, parameters, remove_spike_0, short_name){

  model_rows <- list()
  for(i in seq_along(models)){

    model_row <- list()
    model_row[["Model"]] <- models[[i]][["inference"]][["m_number"]]

    temp_prior_list <- attr(models[[i]][["fit"]], "prior_list")

    for(p in seq_along(parameters)){
      if(is.list(parameters)){
        if(sum(names(temp_prior_list) %in% parameters[[p]]) == 1){
          temp_prior <- temp_prior_list[[parameters[[p]][parameters[[p]] %in% names(temp_prior_list)]]]
        }else if(sum(names(temp_prior_list) %in% parameters[[p]]) == 0){
          temp_prior <- prior_none()
        }else{
          stop("More than one prior matching the specified grouping.")
        }
      }else{
        if(any(names(temp_prior_list) == parameters[p])){
          temp_prior <- temp_prior_list[[parameters[p]]]
        }else{
          temp_prior <- prior_none()
        }
      }
      if(remove_spike_0 && is.prior.point(temp_prior) && temp_prior[["parameters"]][["location"]] == 0){
        model_row[[names(parameters)[p]]] <- ""
      }else if(is.prior.none(temp_prior)){
        model_row[[names(parameters)[p]]] <- ""
      }else{
        model_row[[names(parameters)[p]]] <- print(temp_prior, silent = TRUE, short_name = short_name)
      }
    }
    model_rows[[i]] <- model_row
  }

  summary_table <- data.frame(do.call(rbind, model_rows))
  for(i in 1:ncol(summary_table)){
    summary_table[,i] <- unlist(summary_table[,i])
  }

  colnames(summary_table) <- c("Model", names(parameters))

  # formula parameters are labelled by their term, rendered from the prior
  parameters <- unlist(parameters) # deal with potential matching of multiple parameters withing a name
  for(p in seq_along(parameters)){

    priors <- lapply(models, function(m) attr(m[["fit"]], "prior_list")[[parameters[p]]])
    priors <- priors[!vapply(priors, is.null, logical(1))]
    if(length(priors) == 0L || !nzchar(.bt_label_formula_parameter(priors[[1L]]))){
      next
    }
    colnames(summary_table)[colnames(summary_table) == parameters[p]] <- .bt_label(
      .bt_label_parts_term(parameters[p], priors[[1L]]),
      style = "table"
    )
  }

  return(summary_table)
}
.fit_summary_column <- function(fit_summary, column){

  if(is.null(fit_summary) || !column %in% colnames(fit_summary)){
    return(NA_real_)
  }

  fit_summary[, column]
}
.max_or_na <- function(x){

  if(length(x) == 0 || all(is.na(x))){
    return(NA_real_)
  }

  max(x, na.rm = TRUE)
}
.min_or_na <- function(x){

  if(length(x) == 0 || all(is.na(x))){
    return(NA_real_)
  }

  min(x, na.rm = TRUE)
}
