name: R-unit-tests

on:
  push:
    branches: [main, master, pre-release]
  pull_request:
    branches: [main, master, pre-release]

jobs:
  test:
    runs-on: ${{ matrix.config.os }}
    strategy:
      fail-fast: false
      matrix:
        config:
          - {os: windows-latest, r: 'release'}
    steps:
      - uses: actions/checkout@v4

      - name: Setup R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ matrix.config.r }}

      - name: Install System Dependencies (Linux)
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            libssl-dev \
            libcurl4-openssl-dev \
            libxml2-dev \
            jags

      - name: Install JAGS (Windows)
        if: runner.os == 'Windows'
        shell: cmd
        run: |
          curl -o jags-installer.exe -L https://sourceforge.net/projects/mcmc-jags/files/JAGS/4.x/Windows/JAGS-4.3.1.exe/download
          jags-installer.exe /S
          del jags-installer.exe

      - name: Set JAGS environment variables (Windows)
        if: runner.os == 'Windows'
        shell: cmd
        run: |
          echo JAGS_ROOT=C:\Program Files\JAGS\JAGS-4.3.1>> %GITHUB_ENV%
          echo JAGS_MAJOR_VERSION=4>> %GITHUB_ENV%
          echo PATH=C:\Program Files\JAGS\JAGS-4.3.1\bin;%PATH%>> %GITHUB_ENV%

      - name: Install JAGS (macOS)
        if: runner.os == 'macOS'
        run: |
          brew update
          brew install jags

      - name: Set Environment Variables (macOS)
        if: runner.os == 'macOS'
        run: |
          JAGS_BIN=$(brew --prefix jags)/bin
          echo "JAGS_ROOT=$(brew --prefix jags)" >> $GITHUB_ENV
          echo "PATH=$JAGS_BIN:$PATH" >> $GITHUB_ENV
          echo "PKG_CONFIG_PATH=$(brew --prefix jags)/lib/pkgconfig" >> $GITHUB_ENV

      - name: Install the required packages
        run: |
          options(repos = c(CRAN = "https://cloud.r-project.org"))
          install.packages(c('devtools', 'testthat', 'vdiffr', 'BayesFactor', 'RoBMA', 'runjags', 'rjags', 'rstan'))
          devtools::install()
        shell: Rscript {0}

      - name: Run Unit Tests
        run: |
          devtools::test()
        shell: Rscript {0}
